### ISSUE TITLE
Conflict with official Irony.dll

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#112]
Apparently xenko compiles a [custom Irony.dll](https://github.com/xenko3d/xenko/tree/master/sources/shaders/Irony) that is used in the shader compiler. This creates an conflict that cannot be solved if a project that loads the [official Irony.dll from the nuget](https://www.nuget.org/packages/Irony/). Our project uses Irony as well to parse generic type names.

The reason for the conflict is that the custom Irony.dll from xenko uses the same public token as the official one and has no version set, it's 0.0.0.0.
so the custom Irony project should use a different public key token for the strong name in order to load it with the official one side-by-side in the same process.

**Comment by tebjan** [comment]
The solution might be as easy as generating a new key for the Irony project in xenko. I can test that and make a pull request.

**Comment by xen2** [comment]
@tebjan sure, if it works that way, I would happily accept a PR.

**Comment by tebjan** [comment]
by the way, highly recommended windows explorer tool for assembly inspection:
https://github.com/tebjan/AssemblyInformation/releases
