### ISSUE TITLE
DebugText.Print is not working

### ISSUE THREAD

**Issue by d3metori** [xenko3d/xenko#113]
From example on 'Debug text' `DebugText.Print("My debug text",new Int2(x: 50, y: 50));` throws null reference exception

**Comment by tebjan** [comment]
does the fix mentioned here fixes it for you? https://github.com/xenko3d/xenko/issues/41

**Comment by d3metori** [comment]
idk, i added script in my scene from #41 but still got null reference exception

**Comment by profan** [comment]
this should be resolved by: https://github.com/xenko3d/xenko/commit/b887069aacce1c9cc863232a9137d2bb40f288e1

**Comment by xen2** [comment]
Where do you call `DebugText.Print`? (You can't call it too early, i.e. script ctor).
