### ISSUE TITLE
Improve Build System Epic

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#12]
Right now we build Xenko as a single package.
Ideally we should move on to do something more in line with what NuGet expects:
* One NuGet package per dll
* Use "runtimes" for platforms and graphics API
* Games would move from referencing huge `Xenko` to referencing `Xenko.Engine` and `Xenko.Physics` for example.

Other area of improvements:
* Compiling with PackageReference against a local development version (we currently use this "redirect" concept but it's not great). This might need some improvements/discussion with NuGet team.
* Simplify target files
* Review up to date check
* Possibly cross compile multiple platforms from a single solution (`TargetFrameworks`)

Use cases:
* Create solution from VS & add Xenko from NuGet package manager, then open it with Game Studio
* Use only specific part of Xenko from any Visual Studio project
* Create nuget packages from your code/assets and publish them on nuget so that anybody can use them easily
* People can customize small part of Xenko and only publish the modified part in their own streams.
* Much faster to update (i.e. no need for everybody to redownload sample if we update only a specific part of the engine)

**Comment by DW01** [comment]
A good number of large projects on NuGet (i.e. Discord.NET, Newtonsoft.JSON, etc..) also tend to utilise metapackages to make referencing all components or specific subsets of components easier on the developer. Given how many libraries Xenko creates, this could be an idea.

We could, for example, do this:

- Xenko (overall metapackage)
--- Xenko.Graphics (compartmentalised render backends)
--- Xenko.Editor (Game Studio / "native" UI for editor and extensions)
--- Xenko.Tests (unit testing)
--- etc

as well as individual library packages for the adventurous.

**Comment by weekendkoder** [comment]
will there be a webGL export ?

**Comment by tebjan** [comment]
@weekendkoder this is discussed in: #677

**Comment by weekendkoder** [comment]
@tebjan .. okay. Thx.
