### ISSUE TITLE
Incomplete prerequisites to build source

### ISSUE THREAD

**Issue by Eideren** [xenko3d/xenko#124]
I would love to contribute but cannot anymore, 
Following the readme on a fresh install of windows 7 on a VM with everything by default won't build, we need a version of VC++ because of a missing vcomp100.dll but even after that a bunch of tasks fails:
[Exceptions.txt](https://github.com/xenko3d/xenko/files/2305582/Exceptions.txt)
And a bunch of *.dll metadata file missing and libcore.dll copy failed when rebuilding.
The Xenko.GameStudio.exe generated crashes on launch.

I'm running it on a VM because I can't run it on my main machine anymore, not sure what happened but after a re-installation of visual studio 2017 I couldn't preview scripts or build it anymore; a whole bunch of "project not supported" issues.
I have gone through and uninstalled / deleted every files related to visual studio, re-installed to different locations and with different configurations but this error stays there. Building from cmd>dotnet build/msbuild fails understandably, running xenko from the xenko launcher results in [Exceptions2.txt](https://github.com/xenko3d/xenko/files/2305708/Exceptions2.txt)

The issue could come from newer visual studio versions since I already had one at hand and everything was running fine before re-installation ?

Here are the additional components installed through VS installer on the VM:
```
C# and Visual Basic Roslyn compilers
MSBuild
Static analysis tools
C# and Visual Basic
.NET Framework 4.6.1 SDK
.NET Framework 4.6.1 targeting pack
Text Template Transformation
.NET Framework 4.7 SDK
.NET Framework 4.7 targeting pack
.NET Framework 4.7.1 SDK
.NET Framework 4.7.1 targeting pack
.NET Framework 4.7.2 SDK
.NET Framework 4.7.2 targeting pack
Visual Studio C++ core features
Visual C++ 2017 Redistributable Update
VC++ 2017 version 15.8 v14.15 latest v141 tools
Windows 10 SDK (10.0.17134.0)
Windows Universal CRT SDK
Windows 8.1 SDK
Windows XP support for C++
C++/CLI support
VC++ 2015.3 v14.00 (v140) toolset for desktop
Visual C++ compilers and libraries for ARM
Visual C++ runtime for UWP
.NET Core runtime
.NET Framework 3.5 development tools
NuGet targets and build tasks
.NET Compiler Platform SDK
GitHub extension for Visual Studio
Clang/C2 (experimental)
VC++ 2017 version 15.8 v14.15 Libs for Spectre (ARM)
Visual C++ compilers and libraries for ARM64
VC++ 2017 version 15.8 v14.15 Libs for Spectre (ARM64)
VC++ 2017 version 15.8 v14.15 Libs for Spectre (x86 and x64)
VC++ 2017 version 15.7 v14.14 toolset
VC++ 2017 version 15.6 v14.13 toolset
VC++ 2017 version 15.5 v14.12 toolset
VC++ 2017 version 15.4 v14.11 toolset
C++ Universal Windows Platform tools for ARM64
```

**Comment by Eideren** [comment]
I ended up fixing the installation on my main machine by re-installing the build framework in the assembly cache, looks like it's required when you update VS.
On Visual Studio's dev console execute
`gacutil /u Microsoft.Build.Framework`
To uninstall it and
`gacutil /i "Path To Your visual studio's msbuild\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll"`
To install the newer version.

We still need a version of visual c++ and something else to build assets on a fresh install.

**Comment by tekgoblin** [comment]
Can't edit the UI/Editor for game studio with VS2017 Version 15.8.3. It compiles fine, no issues besides the warnings, just can't actually extend the editor without editing the xaml in a text editor. Is there a known issue for this or should I downgrade to 15.2?

**Comment by xen2** [comment]
@Eideren thanks, I also noticed localization tools didn't work well on my clean config. Will try to fix it so that your custom steps are not required anymore.

**Comment by xen2** [comment]
PS: Might be more than just localization (GNU.Gettext.Msgfmt.exe issue) in your case, seems log also show some other issues.

**Comment by xen2** [comment]
@Eideren Gave a try with a clean Win7 VM and did an update to README: 1cc4d2761db03
Does it work better with those instructions?

**Comment by Eideren** [comment]
@xen2 cleared the VM, re-installed windows, followed the new readme and nope, still won't the editor.
Here's the [very first build's output](https://github.com/xenko3d/xenko/files/2371348/FirstBuild.txt) and [the second one](https://github.com/xenko3d/xenko/files/2371350/SecondBuild.txt)
Third+ are similar to the second one.
Here's the list of installed programs: ![the list of installed programs](https://user-images.githubusercontent.com/5742236/45366830-10906380-b5e0-11e8-891a-ac9c406728f9.png)

I didn't wait for windows to update itself though and I don't think we should expect, even if it isn't safe, other users to do either.

**Comment by Kryptos-FR** [comment]
@Eideren Can you give us the full output? It looks like you only copied the error messages. Also after cleaning the solution, can you first start building the engine, then Xenko.GameStudio (don't try building the whole solution)?

**Comment by Eideren** [comment]
@Kryptos-FR sure, here's the output for [xenko.gamestudio.csproj](https://github.com/xenko3d/xenko/files/2371903/xenko.gamestudio.txt) after cleanup and the output for a [solution rebuild](https://github.com/xenko3d/xenko/files/2371923/solution.txt) just in case.

**Comment by Kryptos-FR** [comment]
In the first log I see that `Xenko.Physics` was not built. Can you try to build it separately and report any errors?

**Comment by Eideren** [comment]
Building [Xenko.Physics](https://github.com/xenko3d/xenko/files/2374642/Xenko.Physics.txt) succeeded and building [Xenko.GameStudio](https://github.com/xenko3d/xenko/files/2374643/Xenko.GameStudio.txt) afterward did as well.
[Running GameStudio](https://github.com/xenko3d/xenko/files/2374644/Running.GameStudio.txt) afterwards still doesn't work.

Installing and running xenko from the installer works though.

**Comment by Eideren** [comment]
After unloading each *.Test project and clearing the bin folder the build still does not succeed but building it twice in a row does though.
Here's the [first try at building the solution](https://github.com/xenko3d/xenko/files/2375102/FirstSolutionBuild.txt)


Now, the crash when loading a project is related to [this exception](https://github.com/xenko3d/xenko/files/2375042/GP10%2BNotSupported.txt), either a lack of driver or VM graphics support. In any case Xenko supports dx9.1 so this exception shouldn't really occur, I created a new issue about it.

**Comment by xen2** [comment]
@Kryptos-FR no the issue wasn't fixed (I thought it was just your setup somehow, but if other people have it I will fix it with higher priority)

**Comment by Eideren** [comment]
@Kryptos-FR so the level is the actual graphics card support while the version is the maximum level that you can achieve by supporting it ? You can run an older graphics card through the feature set of dx9 in dx11 by using the dx9 level ?

**Comment by Eideren** [comment]
I built a new VM just to be sure and can confirm that it builds straight away, great job @xen2 , I'm closing this one off.

**Comment by xen2** [comment]
@Eideren cool, thanks so much for the bug report!
