### ISSUE TITLE
3D Multiplayer Game Engine

### ISSUE THREAD

**Issue by mikrokode** [xenko3d/xenko#126]
Hi,

Can I use xenko to build a multiplayer 3D game like FPS?

**Comment by Kryptos-FR** [comment]
Hi @mikrokode.

Welcome to Xenko and thank you for your interest.

Kindly note that issues in the GitHub repository are intended for reporting bugs or discussing roadmaps and new features.

For inquiries on how to use the engine or other support, please use the [forums](https://forums.xenko.com/), the [gitter channel](https://forums.xenko.com/) or the [Q&A](http://answers.xenko.com/index.html).

Thanks.
