### ISSUE TITLE
New install, cannot open launcher

### ISSUE THREAD

**Issue by wgraham17** [xenko3d/xenko#130]
Just downloaded the 3.0 release from the official website; upon opening the launcher, I immediately get the following error:

> An error occurred while updating the launcher. If the problem persists, please reinstall this application.

I have attempted to reinstall multiple times (and to different locations) to no avail.  Are there any additional logs created I can provide to diagnose or fix the issue?

**Comment by Eideren** [comment]
I have seen this error occur when the launcher fails to get internet access, maybe check your firewall settings ?

**Comment by wgraham17** [comment]
I'm using the standard consumer Windows Firewall; it isn't preventing any outbound traffic. Does the launcher generate any sort of logs or tracing when it hits this error?

**Comment by Kryptos-FR** [comment]
Could you provide more information about your system configuration? OS version, installed .Net runtimes, disks, location where you installed Xenko,  etc.

**Comment by xen2** [comment]
Might be related to #1 and #133
Please download latest launcher from https://xenko.com/download/ and reopen if it still fail.
