### ISSUE TITLE
support for vive trackers

### ISSUE THREAD

**Issue by joreg** [xenko3d/xenko#136]
helo,

i want to add support for [vive-trackers](https://www.vive.com/eu/vive-tracker/). before i go full pullrequest, here my thoughts:

to my understanding those would be unique to OpenVR but still they would be added to the VRDevice class. right?

so in VRDevice.cs right next to:
`public abstract TouchController LeftHand { get; }` 
i would add a 
`public abstract Tracker[] Trackers { get; }` 

i'd add an abstract Tracker class which would be similar to the TouchController class and would add an implementation for it for OpenVR and empty implementations for the other vr-sdks.

please let me know if this is going in the right direction or not or if there other things to consider?

**Comment by xen2** [comment]
Thanks for offering help.
Sure, sounds good to give it a try with this design.

**Comment by joreg** [comment]
here is my PR https://github.com/xenko3d/xenko/pull/213
