### ISSUE TITLE
Conflict with official Irony.dll round 2

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#137]
very sorry for bringing this one up again. as in #112 described, xenko compiles it's own Irony.dll. this conflicts with other libraries that use the official Irony nuget. in my pull request #114 the problem was solved by assigning a new public key token to the custom one of xenko. 

problem now is that with the new build system in VS2017 all assemblies from nugets get copied to the output folder and there you cannot have two files with the same name.

so the question now is, why does xenko need to compile it's own Irony.dll and what are the changes compared to the official one? because the most easy solution would to just switch to the official one for xenko as well.

the second solution which is also quite easy, would be to rename it to Xenko.Irony.dll or so.

**Comment by xen2** [comment]
Sure, let's rename the assembly for now (we can remove the signing key then).
A few points:
1. It's inside Xenko because there is a bunch of changes to it
2. The plan is to get rid of this assembly in the medium term future (#14)
