### ISSUE TITLE
Switch runtime to .NET Standard 2.0

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#139]
- [ ] Check code compatibility
- [ ] Switch to https://github.com/onovotny/MSBuildSdkExtras (needed for multiple runtime identifiers per TFM)
- [ ] Convert Windows runtime to netstandard2.0
- [ ] Decide what to do for Game and Windows projects

**Comment by makotech222** [comment]
Would .Net Core also be supported after this?

**Comment by tebjan** [comment]
.Net Core is a runtime not a software API, but since .Net standard is fully implemented in .net core, yes it would run on machines that have .Net core as runtime installed.

![image](https://user-images.githubusercontent.com/1094716/44620661-b467d880-a898-11e8-82ee-b982928cbaf9.png)
