### ISSUE TITLE
Material shader template opens with double shader key c# files

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#145]
seems they get generated twice or the template is not saved correctly:

![image](https://user-images.githubusercontent.com/1094716/44622494-bf7f3080-a8b9-11e8-8020-ce02c740db8a.png)

![image](https://user-images.githubusercontent.com/1094716/44622502-eb021b00-a8b9-11e8-8b84-67e1ea49cb97.png)

**Comment by xen2** [comment]
Looks like the default .csproj has not been properly updated to 3.0. It should properly include the .xksl with Custom Tool and the .cs files with auto generate flags (excluding all those files from project and reincluding the .xksl file in the project while Xenko VSIX is installed should do the trick).

**Comment by xwellingtonx** [comment]
It seems that the bug is the xenko version that is in the MaterialShader. xkpkg file I will make the change to the latest version and send a PR.

**Comment by xen2** [comment]
Good point, the `.csproj` was actually OK, but not the Xenko dependency which should be 3.0.0.1-dev (similar to all other samples)

**Comment by xen2** [comment]
@xwellingtonx I will do a release this morning so I will just go ahead and fix it, thanks!
