### ISSUE TITLE
[Enhancement] Change skeleton checkboxes to radio buttons in import model dialog

### ISSUE THREAD

**Issue by Kryptos-FR** [xenko3d/xenko#146]
**Good first issue** | 
------------ |
*Issues reserved for newcomers. Consider taking it only if it's your first time working on a feature or a bug in Xenko.*

In the import model dialog, the skeleton options are currently displayed as checkboxes. Since there are all mutually exclusive, radio buttons would be more appropriate.

![importmodel_skeletonoptions](https://user-images.githubusercontent.com/3006525/44623946-49121b00-a919-11e8-8d12-6b0b8e6e8c58.png)

Starting point:
* `ModelAssetTemplateWindow` in `Xenko.Assets.Presentation`
* `ImportModelFromFileViewModel` in `Xenko.Assets.Presentation`

**Comment by xwellingtonx** [comment]
Resolved with PR #184

**Comment by Kryptos-FR** [comment]
Thanks @xwellingtonx. I'll review it.

A note for later: comment first on the issue when you start working on it so we can assign it to you. That will show that someone is working on it and prevent duplicate work in case someone else was also truing to do it.

**Comment by xwellingtonx** [comment]
I'm sorry..
I will comment next time before to do any issue.

**Comment by Kryptos-FR** [comment]
No worries. That is a rule we should make visible in a document or wiki.

**Comment by xen2** [comment]
@Kryptos-FR good point. just started some [contributing guidelines](https://github.com/xenko3d/xenko/blob/master/docs/CONTRIBUTING.md) (github adds link to it in side panel when creating new issue)

**Comment by Kryptos-FR** [comment]
@xen2 I wonder, shouldn't we mark issue with "help wanted" only when nobody is working on it and remove it once it has been assigned to someone?
Also for some reason I can't assign @xwellingtonx to that issue. Is it because it is the first contribution?

**Comment by xen2** [comment]
@Kryptos-FR it's because he was not added as a collaborator yet (github doesn't allow to assign issues to people that are not collaborators, quite annoying)
> You can only create assignments for yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.
