### ISSUE TITLE
Typo in PhysicsEngineFlags

### ISSUE THREAD

**Issue by Kryptos-FR** [xenko3d/xenko#152]
**Good first issue** | 
------------ |
*Issues reserved for newcomers. Consider taking it only if it's your first time working on a feature or a bug in Xenko.*

`PhysicsEngineFlags` has a value spelled `ContinuosCollisionDetection` instead of `ContinuousCollisionDetection`.

Because that value is used in an asset (here `PhysicsSettings` which is serialized in `GameSettingsAsset`), there is a need to write an asset upgrader.

**Comment by xen2** [comment]
Wasn't there an attribute to rename stuff with Yaml serialization? (Might work only for properties, not sure about enum)
