### ISSUE TITLE
Global game Scripts

### ISSUE THREAD

**Issue by RevolveDE** [xenko3d/xenko#154]
Just wondered about implementing global scripts in the game.
Would be really useful for someone who is working with a 100% Network-based game.

For example, if you connect your game via an entity script to a c# tcpListener via tcpClient it could happen while destroying or deleting this entity from your scene or moving to another scene that you lose connection to the TCP socket.

Is there any way to achieve a script like this? (didn't find one)

**Comment by Kryptos-FR** [comment]
You don't need a script for that. Just a regular c# class that for example implements the singleton pattern.

**Comment by xen2** [comment]
@RevolveDE I am closing this issue. If @Kryptos-FR answer is not good enough, please ask again in the [forums](https://forums.xenko.com) as this is a more appropriate place for discussions/help requests.
