### ISSUE TITLE
Make move camera on left mouse click drug (as in unity hand tool move)

### ISSUE THREAD

**Issue by nikserdev** [xenko3d/xenko#156]

**Comment by Kryptos-FR** [comment]
Why?

**Comment by nikserdev** [comment]
I want to create a 2d top-down shooter, and to place 3d objects on the map, I think it will be convenient to scroll the 2d level in the editor with a left mouse button in the current 2d plane (XY). how can I navigate in the editor in one 2D plane now?

**Comment by Kryptos-FR** [comment]
Have a look at https://doc.xenko.com/latest/en/manual/game-studio/navigate-in-the-scene-editor.html

You can display a 2D plane by clicking the corresponding side on the **view camera gizmo** in the top-right of the Scene Editor.

**Comment by nikserdev** [comment]
Pan action exactly what i needed ) Thank you. 
It would be more convenient to assign pan action to the left mouse button. what do you think?

**Comment by Kryptos-FR** [comment]
> It would be more convenient to assign pan action to the left mouse button. what do you think?

I think it was the case in the past but it caused issues with other actions bound to the left-click (like selection). Also there was (is?) a plan to implement rectangle selection with the left mouse button.

Of course, it all could be configurable, but that would need to rework a the settings and shortcut configurations, which is a bit messy at the moment.

**Comment by nikserdev** [comment]
Rectangle selection with the left mouse button is good idea.
Thank you for your responses
