### ISSUE TITLE
New script adds ".Game" namespace -> error "Game" is namespace is use like a type

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#163]
this is pretty unfortunate and i'd give it high priority because every beginner that just adds a script gets this. might be the default behavior of visual studio. the namespace should probably just be "MyGame(.AssetFolder)" instead of "MyGame.Game(.AssetFolder)". also in the forums: https://forums.xenko.com/t/mygameapp-namespace-used-like-type/1552

related to #128

**Comment by Kryptos-FR** [comment]
Fixing the default template with a fully qualified namespace should be the easiest way. PR welcome :smiley:

**Comment by xen2** [comment]
I would rather fix it the underlying issue: root namespace from xkpkg/csproj is not used anymore, resulting in scripts being created with `MyGame.Game`  rather than `MyGame`

**Comment by Kryptos-FR** [comment]
Those are not invalid. It is the default behavior in any project/assembly in Visual Studio: default namespace = assembly name. So I would rather keep that since it is the expected behavior.

But it's debatable.

**Comment by xen2** [comment]
Being quite critical, I will take care of that one right away

**Comment by xen2** [comment]
Fixed (note: it now also creates namespaces properly in subfolders).

**Comment by tebjan** [comment]
that was quick, excellent. thanks a lot!

**Comment by xen2** [comment]
@Kryptos-FR sorry, misread your message (I thought you didn't see the RootNamespace). I agree with you on the point that project/assembly better have same namespace, so we should probably drop the `.Game` from assembly name at some point to have them match (in a separate PR/issue).
Not sure about platform projects (Windows, etc...) though.
