### ISSUE TITLE
Reenable Linux support

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#17]
Asked by several people already (twitter, forums, gitter)

**Comment by xen2** [comment]
Being the most upvoted issue on GitHub, I started to give it a quick try.
Looks like it should be quick to fix, everything seems to compile fine against .NET Core 2.1:

![image](https://user-images.githubusercontent.com/527565/44567957-a2f6d180-a7af-11e8-8dcf-8c4af15ab81d.png)

**Comment by Kryptos-FR** [comment]
@xen2 Not directly related, but should we move all runtime libraries to target .Net standard 2.0 instead of 4.5 currently?

**Comment by xen2** [comment]
added #139
