### ISSUE TITLE
Avoid assuming negative-Z gravity

### ISSUE THREAD

**Issue by DW01** [xenko3d/xenko#170]
**Release Type**: Both

**Version**: any future

**Describe the feature**
Not so much a bug report as a feature request, but the engine should avoid explicitly assuming a negative Z vector for gravity. Currently, the engine assumes negative-Z gravity (see Additional context for example).

**To Reproduce**
Not applicable.

**Expected behavior**
User-configurable gravity vector, possibly also localisable to volume triggers. Useful for, among other things, proper vehicle behavior through structures such as loops.

**Additional context**
CharacterComponent.cs (part of Xenko.Physics) assumes negative-Z as gravity, but uses a full Vector3 internally:

        /// <summary>
        /// Gets or sets if this character gravity
        /// </summary>
        /// <value>
        /// true, false
        /// </value>
        /// <userdoc>
        /// The gravity force applied to this character
        /// </userdoc>
        [DataMember(95)]
        public float Gravity
        {
            get
            {
                return gravity;
            }
            set
            {
                gravity = value;

                if (KinematicCharacter != null)
                {
                    KinematicCharacter.Gravity = new Vector3(0.0f, value, 0.0f);
                }
            }
        }

Perhaps make all three components of the Vector3 configurable?

**Comment by xen2** [comment]
Sure, make sense, esp. since `Gravity` is already a `Vector3` in both `RigidbodyComponent` and `Simulation`.
Feel free to submit a PR for that.

**Comment by DW01** [comment]
Started on this here DW01/xenko@0e24c2528681b5bc410cbdc2659a8b7f8be45b31

I'm not a UI guy, so my attempts at WPF XAML editing would probably suck. This is based on the same initialiser from `RigidbodyComponent`.
