### ISSUE TITLE
CPU/GPU is working abnormally when the window is minimized

### ISSUE THREAD

**Issue by EssenRoc** [xenko3d/xenko#183]
**Release Type**: Both

**Version**: 3.0.0.4

**Platform(s)**: Windows

**Describe the bug**
CPU/GPU is working abnormally when the window is minimized.

**To Reproduce**
1. Create a project
2. Run project
3. Minimize window

**Expected behavior**
I think CPU/GPU should not be so exaggerated.

**Screenshots**

![gif](https://user-images.githubusercontent.com/12685126/44970306-90388580-af83-11e8-9f4d-dc6e397f1df9.gif)

**Comment by domske** [comment]
Confirmed. I tested the same with similar results.

**Comment by Eideren** [comment]
Xenko doesn't follow `GraphicsDevice.Presenter.PresentInterval` value while minimized : the game loop is ran at a rate higher than what the display syncs to even though it still runs GraphicsDevice.Presenter.Present(). 

Perhaps related to [our use of SharpDX's SwapChain.TryPresent](https://github.com/xenko3d/xenko/blob/3e89094a076aa5d64344af5aa64a13847f32d910/sources/engine/Xenko.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs#L154) ? Not sure how presenting a frame acts in general for minimized windows.

Weirdly enough, for me, it's also hitting the GPU far harder than `Immediate` does. 
On `Immediate` the process' game-loop runs at ~2ms/loop, while minimized it runs at ~0.05ms/loop, so the GPU is probably not actually rendering, we're just prodding it and SharpDX's TryPresent might be returning that the graphics device is disconnected ?

Here's the presenter callstack:
```
Xenko.Games.GameBase.Run(GameContext)
Xenko.Games.GameWindowWinforms.Run()
Xenko.Games.WindowsMessageLoop.Run(Control, RenderCallback, Boolean)
Xenko.Games.GamePlatform.OnRunCallback()
Xenko.Games.GamePlatform.Tick()
Xenko.Games.GameBase.Tick()
Xenko.Games.GameBase.TickInternal()
Xenko.Engine.Game.EndDraw(Boolean)
Xenko.Games.GameBase.EndDraw(Boolean)
Xenko.Games.GraphicsDeviceManager.EndDraw(Boolean)   (from Xenko.Games.IGraphicsDeviceManager)
Xenko.Graphics.SwapChainGraphicsPresenter.Present()
SharpDX.DXGI.SwapChain.TryPresent(Int32, PresentFlags)
```

It's outside of my expertise though, so I hope this post could point someone else in the right direction.

**Comment by Eideren** [comment]
I'm working on a frame rate limiter since EssenRoc closed his PR. I'm almost done, just a couple of tweaks and I'll PR.
