### ISSUE TITLE
Auto hide panel does not uncheck the option in the view menu

### ISSUE THREAD

**Issue by xwellingtonx** [xenko3d/xenko#191]
**Release Type**: Both

**Version**: 3.0.0.5

**Platform(s)**: Windows

**Describe the bug**
If you auto hide any painel in game studio will be not uncheck the option in view menu.

**To Reproduce**
1. Open a project in Game Studio
2. Auto hide any painel
3. Open view menu

**Expected behavior**
It is expected that when a panel is hidden the option in the view menu is unckeck.

**Screenshots**
![bug3](https://user-images.githubusercontent.com/10274446/45265979-3ecc4280-b42a-11e8-868a-fc0c49ea8d76.gif)

**Log and callstacks**
Not applicable

**Additional context**
Not applicable

**Comment by Kryptos-FR** [comment]
That is the expected behavior. The entry is unchecked when the panel is closed, not when it is hidden.

**Comment by xwellingtonx** [comment]
Sorry i thought it was not..

**Comment by Kryptos-FR** [comment]
No worries. It is always better to report something when you have a doubt. Even if the current behavior is correct, it can sometimes start a discussion on how things can be improved.
