### ISSUE TITLE
Add "Show in Explorer" right click option in Recent projects.

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#197]
Just like in the launcher, it would be good to have a context menu on recent projects "Show in Explorer".

![image](https://user-images.githubusercontent.com/527565/45397144-9ca29980-b679-11e8-9664-67cf9eceacf5.png)

**Comment by xwellingtonx** [comment]
@xen2, This issue has impact on #195. I will do the both for prevent any problem.

**Comment by xen2** [comment]
@xwellingtonx Great, thanks!

**Comment by xen2** [comment]
Fixed by #208.
