### ISSUE TITLE
[Editor] Wrong icon for "Move selected sprites down" option in sprite sheet editor.

### ISSUE THREAD

**Issue by justStand** [xenko3d/xenko#199]
**Release Type**: Official Release

**Version**: 3.0.0.4

**Platform(s)**: Windows

**Describe the bug**
![image](https://user-images.githubusercontent.com/6134159/45436203-12e9d080-b667-11e8-9976-2c3f3bc6d9ab.png)

**To Reproduce**
Create a sprite sheet. Double click to edit.

**Expected behavior**
Icon should be upside down.

**Comment by xwellingtonx** [comment]
I will fix it.
