### ISSUE TITLE
Feature Request: Implement AutoRecovery/Backup so broken projects are recoverable.

### ISSUE THREAD

**Issue by aurodev** [xenko3d/xenko#225]
**Release Type**:Any

**Version**: Any

**Platform(s)**: Windows

**Describe the bug**
Projects break, **_frequently_**, **in unrecoverable way**s, despite forcing asset and code rebuild.

**To Reproduce**
1. Modify a project until it breaks. Shouldn't take very long.
2. Observe the error/warning spam
3. Remove or revert the offending changes to the project, if that can even be determined.
4. Manually clean the asset cache in multiple locations and have VS clean the project code cache to force rebuilds.
5. Observe the continued error/warning spam which can be permanent even following multiple, extensive, cleanings.

**Expected behavior**
Projects should not break in unrecoverable ways. If the (should be) rare breakage occurs it should be possible to recover a broken project without manual cache cleaning. At the very least the choice to clean and rebuild should 1) be available from within GameStudio and 2) restore a broken project to a previous working configuration.

**Screenshots**
<insert big screen shot of warning and error spam HERE>

**Log and callstacks**

**Additional context**
Xenko breaks small test projects following simple changes to the renderer and assets. Even removing the offending assets, cleaning **all** the cache locations and reverting the changes to render settings doesn't remove the warning spam in most cases. It is almost hit or miss as to whether a project will survive  a significant change to an asset or setting. This has been our experience following multiple test projects. Until Xenko is either more stable or the docs provide an updated restoration protocol the core developers might consider implementation of a periodic project backup system with a configurable interval.

**Comment by jonstelly** [comment]
I haven't had quite the bad luck that it sounds like you're having but I have gotten to a couple odd states where I got errors that I couldn't figure out.

Not as a fix, but maybe as a bit of a workaround: I've found keeping the Xenko files checked into git and making semi-frequent commits as I make a change and test it has given me a good route for recovery.  The Xenko files you'd want to check in are all text-based and it can be nice to review the diffs for what changed before committing.

**Comment by Kryptos-FR** [comment]
That's where using a version control system works fine. Just create a git repository for your project and commit often.

**Comment by aurodev** [comment]
> 
> 
> I haven't had quite the bad luck that it sounds like you're having but I have gotten to a couple odd states where I got errors that I couldn't figure out.
> 
> Not as a fix, but maybe as a bit of a workaround: I've found keeping the Xenko files checked into git and making semi-frequent commits as I make a change and test it has given me a good route for recovery. The Xenko files you'd want to check in are all text-based and it can be nice to review the diffs for what changed before committing.

Good point, actually (honestly) did that staging + commiting every single untracked file.  :D
Will be nice when Xenko is a bit more stable.  Lots of potential.

**Comment by xen2** [comment]
While there is definitely lot of things we have to do to improve project stability/corruption, I don't think it's a good idea to venture into making a full incremental/live backup system (it's huge and not trivial to do well, we have limited resources and other products such as version control & backup software/NAS can do that). I would prefer to focus our resources on making sure those corruptions don't happen in the first place and encourage user to do proper & safe regular backups.

Longer term we could consider a one-time backup on potentially breaking upgrade like Visual Studio does. However, for now we display a message urging user to backup before Xenko upgrade and it will likely stay like that for now considering the huge amount of other things to do.

I guess I will close this issue for now. We could reopen if project gets bigger.
