### ISSUE TITLE
VS Plugin does not install

### ISSUE THREAD

**Issue by TomGroner** [xenko3d/xenko#23]
After upgrading to Xenko v3 my visual studio plugin was not generating .cs files for shaders and threw an error when trying to open Xenko Studio so I attempted to re-install it. When trying to install it from the launcher it briefly shows an animation in the progress bar, then reverts back to the install button.

I opened up fiddler to see what it may be trying to do and notice that the package it's pinging is 404 Not Found.

Request
```
GET https://api.nuget.org/v3/registration3-gz-semver2/xenko.visualstudio.package/index.json HTTP/1.1
[removed other headers]
```

Response:
```
HTTP/1.1 404 Not Found
[removed other headers]

<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
Time:2018-08-03T10:58:02.7015548Z</Message></Error>
```

**Comment by xen2** [comment]
It's not been published yet (forgot about it, sorry).
Also it seems like it's not working properly right now so I will fix it and make sure it works before releasing it (soon hopefully).

**Comment by xen2** [comment]
It's now released, let me know if you run into any issues.

**Comment by TomGroner** [comment]
Working for me now, thank you!
