### ISSUE TITLE
Audible clicks at the end of encoded sound effects

### ISSUE THREAD

**Issue by guygodin** [xenko3d/xenko#235]
**Release Type**: GitHub

**Version**: 3.0.0.5

**Platform(s)**: Android

**Describe the bug**
Encoded sound effects have audible clicks at the end.

**To Reproduce**
1. Add a sound effect with a short wav (1s length)
2. Build project, deploy and programmatically play the sound.
3. The sound will click when it reaches the end

**Expected behavior**
There shouldn't be pops or clicks in encoded sounds

**Additional context**
I've looked into the SoundAssetCompiler and tried to remove metadata from the generated temp file (by passing "-map_metadata -1" to ffmpeg. I've also made sure the source sound didn't have any clicks in the original signal. I've tried increasing the length of the source wav (with silence at the beginning and end of the signal). I've also double checked that there are no uncleared buffers in the SoundAssetCompiler code. Tried 3 different Android devices running on different versions. I'm running out of ideas. The sounds always produce a click at the end when played back. Only tested on Android as my project doesn't run on Windows. Any help would be appreciated. Thanks!

**Comment by guygodin** [comment]
Here's an example of sound which will reproduce the bug:
[Click.zip](https://github.com/xenko3d/xenko/files/2481507/Click.zip)

**Comment by Kryptos-FR** [comment]
Could be related to compression of very short wave sounds. I think in those case, it is better to not compress them.

Also @xen2 do we still use Opus/Celt for sounds? Or did we move to only use ffmpeg in all cases?
https://doc.xenko.com/latest/en/manual/audio/audio-asset-properties.html probably needs to be amended.

**Comment by mrboni** [comment]
I'm getting clicks (at the loop point) when looping sounds of any duration, and either compressed or uncompressed
