### ISSUE TITLE
Xenko Launcher closes immediately when network is unavailable.

### ISSUE THREAD

**Issue by profan** [xenko3d/xenko#250]
**Release Type**: Official Release

**Version**: 3.0.0.6

**Platform(s)**: Windows

You can't launch Xenko through the launcher with no network connectivity, it closes immediately.

**To Reproduce**
1. Start the Xenko launcher with no network connectivity.

**Expected behavior**
I expect it to still be possible to use the launcher but functionality depending on network connectivity to not operate, putting itself in a downgraded mode is perfectly acceptable.

**Screenshots**
![image](https://user-images.githubusercontent.com/2816340/47879710-959a3b00-de21-11e8-88e6-bc4523cf0e50.png)

**Comment by Kryptos-FR** [comment]
That should already be the case. Looks like a regression.

**Comment by profan** [comment]
This doesn't seem to be occurring anymore since the latest update, so I'm closing this one!

Thanks!

(below the result expected, yay!)
![image](https://user-images.githubusercontent.com/2816340/48874151-049bfb80-edf2-11e8-9909-8f2ab51afe2a.png)
