### ISSUE TITLE
Crash Report server error (probably forgot to replace the crash report server)

### ISSUE THREAD

**Issue by pikachuk** [xenko3d/xenko#26]
Hello, i'm writing this because i encountered this issue while trying to submit a crash report with xenko
![sans titre](https://user-images.githubusercontent.com/16335601/43660414-37f97a00-975f-11e8-9974-d98147b25e19.png)

I think it's caused by the fact that Xenko is no longer supported by Silicon Studio so Silicon Studio's crash report server can't be reached anymore

In the current case, xenko crashed while trying to load a model from a .blend file but i don't have the log anymore since after clicking "send" it closed the crash report window so i wasn't able to retrieve the log

**Comment by Refsa** [comment]
The MetricsClient(Xenko.Metrics.MetricsClient) class is not implemented. Seems like that is responsible for dispatching crash reports.

You are probably right in that the url is wrong, there probably isn't any established endpoint for crash reports yet.
