### ISSUE TITLE
VerificationException in Irony.Parsing.CoreParser after update to C# 7.2

### ISSUE THREAD

**Issue by svenberra** [xenko3d/xenko#266]
**Release Type**: GitHub

**Version**: 3.0.0.7 (2eb9a6f)

**Platform(s)**: Windows 7 using Visual Studio 2017 Pro(15.9.0)

**Describe the bug**
I get a System.Security.VerificationException from Irony.Parsing.CoreParser as soon as the shader for a material is parsed.

**To Reproduce**
1. Launch the Editor and create a New Game project using default settings.

**Log and callstacks**

`var first = Context.ParserStack[Context.ParserStack.Count - childCount];`

[callstack.txt](https://github.com/xenko3d/xenko/files/2585968/callstack.txt)

**Comment by tebjan** [comment]
hi @svenberra i've made a PR that reverts the commit and it was accepted already.  #268

**Comment by svenberra** [comment]
Now it works again.
Thank you. :)
