### ISSUE TITLE
Error while updating the installer

### ISSUE THREAD

**Issue by Patrick-Spiegel** [xenko3d/xenko#270]
**Release Type**: Official Release

**Version**: Current

**Platform(s)**: Windows 10

Hello there,

I have tried to install xenko (first time) but when opening the launcher there always pops up the window saying "An error occurred while updating the launcher. If the provlem persists, reinstall this application"

Is there any way I can find out what the issue is eg. Log Files? Does the launcher use an IP on Port 80? IPv4 is not allowed to connect to port 80, but I guess that you are using 443 if I can trust the network manager. 

![perfmon_2018-11-18_20-45-39](https://user-images.githubusercontent.com/35311793/48677312-41a68a80-eb73-11e8-89a5-56c65cc00315.png)
![cmd_2018-11-18_20-47-53](https://user-images.githubusercontent.com/35311793/48677313-43704e00-eb73-11e8-9948-aa56b4ef3ccd.png)

The last IP cannot be connected. I don't know whether there is some kind of load balancer that disallows pings but I cannot ping it. I don't know if its a bad sign.

**Comment by xen2** [comment]
Probably duplicate of #1 #131 and #130.
I have just uploaded a new launcher that should fix those.

Please download latest launcher from https://xenko.com/download/ and let us know if it fixed the issue.
Otherwise, it should at least display more info.

**Comment by Patrick-Spiegel** [comment]
Yeah it was that issue. I thought it should have been fixed when I saw the date.
