### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Degaron** [xenko3d/xenko#278]
Where to download MIT Xenko?

I recently downloaded Xenko and it was written in license that the developer of Xenko would cooperate with law enforcement agencies or something similar, sue and etc.

But this is unacceptable for an open project.

**Comment by xen2** [comment]
Hello,

License is MIT (the one you downloaded too).

You probably reference to the [Privacy Policy](https://github.com/xenko3d/xenko-website/blob/master/legal/privacy-policy.html) which is mostly a leftover from when the engine was commercial and needs to be updated to reflect new state of the project. Sorry for the confusion.

**Comment by xen2** [comment]
I have updated the [Privacy Policy](https://xenko.com/legal/privacy-policy/)
Should be much less scary.
Please reopen issue if you still see points of concerns.

**Comment by tebjan** [comment]
@Degaron metrics are public: https://metrics.xenko.com/

**Comment by Degaron** [comment]
Each user should be able to disable this feature.

**Comment by tebjan** [comment]
you can make a pull request that adds an option, if you feel that that it is needed: https://github.com/xenko3d/xenko/tree/master/sources/metrics

**Comment by Degaron** [comment]
I did it here, and now the developers will decide.

**Comment by Degaron** [comment]
And where are the official compiled versions?
Where is windows 64 bit?
Today, no one will compile the program, it's just absurd.

**Comment by Eideren** [comment]
https://xenko.com/download/
Please, stick to the issue's subject.

**Comment by bluesaka111** [comment]
All of the annoying vibration because of this?

If you affair of metrics that Xenko collect then don't use it. Seriously.

If you are affair of compiling the source code then visit xenko.com/download. 

32 bit or 64 bit architecture program run just fine on x64 architecture Windows!

**Comment by xen2** [comment]
I am totally fine to make the metrics collection optional (somebody need to spend time to do it, I have some other things that are higher priority).
Users would still have to accept it if they send a crash report though.
