### ISSUE TITLE
ColliderShapeAsset does not compile when necessary

### ISSUE THREAD

**Issue by EternalTamago** [xenko3d/xenko#283]
**Release Type**: Official Release

**Version**: 3.0.0.6

**Platform(s)**: Windows

**Describe the bug**
The model file refered by ColliderShapeAsset(ConvexHull's Model) was updated by an external tool but ColliderShapeAsset was not compiled to update.

You need to delete the Cache directory to update it.
Or rename the ColliderShapeAsset.

**To Reproduce**
1. Add a ColliderShapeAsset as ConvexHull and set a ModelAsset as the source.
2. Add StaticColliderComponent to an entity and add the ColliderShapeAsset to StaticColliderComponent's ColliderShapes.
3. Update the model file of the ModelAsset with an external tool.

**Expected behavior**
ColliderShapeAsset is compiled by updating the model file.(Like ModelAsset)

**Screenshots**
1.
![1](https://user-images.githubusercontent.com/13661631/49368080-36398e80-f731-11e8-91a2-3cf3919fa9b3.png)
2.
![2](https://user-images.githubusercontent.com/13661631/49368084-3a65ac00-f731-11e8-8cf7-e06a870a2ae7.png)
3.
![3](https://user-images.githubusercontent.com/13661631/49368094-3df93300-f731-11e8-8c88-d2a6be4329a2.png)
Result.
![results](https://user-images.githubusercontent.com/13661631/49368104-42bde700-f731-11e8-9009-89353c8b37f6.png)

**Log and callstacks**

**Additional context**

**Comment by EternalTamago** [comment]
I think so too but those data can not recover when the Cache directory was lost.
This might confuse us.

**Comment by xen2** [comment]
@EternalTamago @Kryptos-FR 
Yes agree, if anything like that, it shouldn't be in cache but it should be an explicit export to a file that can be used as a source and committed.
