### ISSUE TITLE
Tabs can no longer be closed.

### ISSUE THREAD

**Issue by antonyjones67** [xenko3d/xenko#286]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Github

**Version**: Version number and/or git branch
3.1.0.1 dev

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows
**Describe the bug**
Cannot close any Tabs. No close button.

**To Reproduce**
1. Just pull up Game Studio editor. MainScene editor Tab does not have a close button.

**Expected behavior**
Based on older versions of Xenko the Tabs could be closed.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by Kryptos-FR** [comment]
Screenshots would be really useful here.

**Comment by xen2** [comment]
don't think screenshot is needed, doesn't seem hard to repro.
(FYI this happens in master which is quite exp)

**Comment by Kryptos-FR** [comment]
Screenshots are still good for history purpose: later when we encounter a similar issue we can compare.

**Comment by xen2** [comment]
Fixed by a006a765
