### ISSUE TITLE
Launcher 2.0.2 update to 3.0.1 error

### ISSUE THREAD

**Issue by diondokter** [xenko3d/xenko#288]
Downloaded the latest launcher via the homepage ([https://xenko.com/files/XenkoSetup.exe](https://xenko.com/files/XenkoSetup.exe)).

The download leads to version 2.0.2.
When the launcher starts, 3 windows pop up:

1. Xenko 3.0: Free and fully open source!
2. It seems you do not have any version of Xenko installed...
3. New version of Xenko Launcher is being downloaded.

Number 3 then quickly closes and changes to an error popup with the text:

> An error occurred while updating the launcher. If the problem persists, please reinstall this application.
Details: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Xenko.Launcher.3.0.1' from source 'Syncfusion Xamarin Packages'. ---> NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Xenko.Launcher.3.0.1' from source 'Syncfusion Xamarin Packages'. ---> NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin/Packages(Id='Xenko.Launcher',Version='3.0.1')' returned an unexpected status code '500 Internal Server Error'. at NuGet.Protocol.V2FeedParser.<>cDisplayClass50_0.<<LoadXmlAsync>b1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d14`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.V2FeedParser.<LoadXmlAsync>d50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.V2FeedParser.<QueryV2FeedAsync>d49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.V2FeedParser.<GetPackage>d37.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.DependencyInfoResourceV2Feed.<ResolvePackage>d4.MoveNext() --- End of inner exception stack trace --- at NuGet.Protocol.DependencyInfoResourceV2Feed.<ResolvePackage>d4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<GatherPackageFromSourceAsync>d28.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<GatherPackageAsync>d27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<>cDisplayClass26_0.<<StartWorkerTasks>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<ProcessResultsAsync>d25.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<StartTasksAndProcessWork>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<GatherAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.ResolverGather.<GatherAsync>d20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d66.MoveNext() --- End of inner exception stack trace --- at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d66.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.Core.Packages.NugetStore.<InstallPackage>d76.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.Services.SelfUpdater.<UpdateLauncherFiles>d4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.Services.SelfUpdater.<>cDisplayClass3_0.<<SelfUpdate>b0>d.MoveNext()

After closing the popup, the launcher closes.

It seems that there is a new version of the launcher: [Committed here](https://github.com/xenko3d/xenko/commit/e446678a90fc839feba266043f22bbe09bc21cca)

The launcher tries to contact an obviously wrong url:
> http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin/Packages(Id='Xenko.Launcher',Version='3.0.1')

I can confirm the erroneous behaviour with WireShark.

It seems there are two fixes:
1. Update the launcher download to version 3.0.1
2. Patch the old launcher to use a correct url

For now, this issue means that I can't use Xenko.

Computer specs:

| Item | Value |
| --- | --- |
| OS Name | Microsoft Windows 10 Home 64-bit |
| Version | 10.0.17763 Build 17763 |
| Processor | Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 4101 Mhz, 4 Core(s), 8 Logical Processor(s) |
| Installed Physical Memory (RAM) | 16,0 GB |
| GPU | NVidia GTX 1060 6GB |
| Video driver version | 416.94 |

**Comment by xen2** [comment]
For user facing the issue, please upgrade to latest launcher by downloading setup again from https://xenko.com/download
Closing with this resolution.
