### ISSUE TITLE
Release notes are not displayed in the launcher

### ISSUE THREAD

**Issue by Kryptos-FR** [xenko3d/xenko#296]
**Release Type**: Official
**Version**: Launcher v3.0.3

**Describe the bug**
Release notes are not visible in the launcher.

**To Reproduce**
1. Start the launcher
2. On any version, click on the left-most button to display the release notes of any version

**Expected behavior**
The release notes panel slides from the right and displays them.

**Additional context**
As far as I remember, it was working before the last release of the launcher (should have been v3.0.2 or v3.0.1).

**Comment by xen2** [comment]
It's because I didn't push new doc (yet) to https://doc.xenko.com/3.1

**Comment by xen2** [comment]
OK I can confirm that I pushed version built with some source code changes I didn't notice (it was pushed in emergency to have more diagnostic when that RenderDocPlugin package was failing on nuget.org). 
Lesson learnt, always build from source server :)

**Comment by xen2** [comment]
Fixed, thanks for the report!
