### ISSUE TITLE
Latest version of visual studio plugin crashes visual studio when trying to manage nuget packages

### ISSUE THREAD

**Issue by justStand** [xenko3d/xenko#298]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta01-0313

**Platform(s)**: Windows

**Describe the bug**
Visual studio becomes unresponsive when trying to manage nuget packages.

**To Reproduce**
1. Rightclick on any project / solution and select manage nuget packages.

**Comment by Kryptos-FR** [comment]
Xenko plugin doesn't deal at all with nuget packages.

**Comment by xen2** [comment]
Good catch, looking into it.
