### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by ShalokShalom** [xenko3d/xenko#306]
I see F# as a viable option for functional programmers. Its declarative approach is especially appealing to not-yet programmers and people who like to think this way. 

Since its a .Net language is it easy to implement. 

It is also one of the most loved programming languages in the world: 
https://insights.stackoverflow.com/survey/2016#technology-most-loved-dreaded-and-wanted

**Comment by tebjan** [comment]
if you want, you can already use F# in a xenko project. since it is basically a .NET solution file, you can open it with visual studio and add a F# project to the solution, reference xenko packages as you need and use the F# project as library in your game project.

**Comment by ShalokShalom** [comment]
Ok, cool. Where is the downside? And why is it not advertised?

**Comment by ShalokShalom** [comment]
If I cant use Linux, I am not interested.
