### ISSUE TITLE
Clicking "Start 3.0.0.6" crashes the launcher.

### ISSUE THREAD

**Issue by faintdeception** [xenko3d/xenko#307]
**Release Type**: Official Release

**Version**: 3.0.0.6

**Platform(s)**: Windows 10

**Describe the bug**
The launcher opens correctly, but when I click "Start 3.0.0.6" the application crashes and asks if I would like to report the error, clicking the send button in the error report dialog does not seem to be working though.

**To Reproduce**
1. Run the Xenko launcher as administrator
2. Click Start 3.0.0.6
3. Attached stack trace:
[xenko stack.txt](https://github.com/xenko3d/xenko/files/2716677/xenko.stack.txt)
 

**Expected behavior**
The new project creation wizard should continue.

**Comment by tebjan** [comment]
cannot confirm, works fin here. could be something with your setup... did you try uninstall everything and then re-install from scratch?

**Comment by xen2** [comment]
Looking at the log, it looks like it's starting 3.1 rather than 3.0.

**Comment by faintdeception** [comment]
I attached the wrong log, I think the error is the same either way, but I'll try a fresh install.
https://github.com/xenko3d/xenko/issues/307#issuecomment-450600121

**Comment by faintdeception** [comment]
The error persists after a fresh install and reboot, I'll give it a try on a different machine.

**Comment by faintdeception** [comment]
The issue is resolved in 3.1.0.1-beta01-0349 so I'm going to close this.

**Comment by xen2** [comment]
cool, thanks!
