### ISSUE TITLE
Engine build: Build error 9009 with locate-devenv in MS Studio 2017

### ISSUE THREAD

**Issue by phr00t** [xenko3d/xenko#311]
**Release Type**: GitHub clone

**Version**: As of Jan 5th, 2019

**Platform(s)**: Windows 10 x64

**Describe the bug**
I believe I installed all dependencies to build Xenko. I opened up Xenko.sln in the build/ directory with Visual Studio 2017. The "error list" shortly appears with this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""..\..\core\Xenko.Core.Tasks\bin\Debug\net472\Xenko.Core.Tasks.exe" locate-devenv "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"" exited with code 9009.	Xenko.VisualStudio.Package.Tests	D:\Phr00tsSoftware\XenkoSource\xenko\sources\tools\Xenko.VisualStudio.Package.Tests\Xenko.VisualStudio.Package.Tests.csproj	70	

The folders do exist (e.g. MSBuild/15.0/Bin/MSBuild.exe is there)... so why is the above failing?

**EDIT:** It looks like Xenko.Core.Tasks.exe doesn't exist...

**To Reproduce**
0. Install all prerequisites 
1. git clone current master branch
2. Open Xenko.sln with Visual Studio 2017
3. Look at the error in the solution

**Expected behavior**
No errors & able to build the project.

**Comment by Kryptos-FR** [comment]
You realize that you have to build the solution to have the executables.

**Comment by phr00t** [comment]
I assumed I wouldn't be able to build a project with errors. I went and did a build now, and now it ballooned to 1228 errors. Most of them look like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\core\Xenko.Core\bin\Debug\net45\Xenko.Core.dll' could not be found	Xenko.Core.IO	D:\Phr00tsSoftware\XenkoSource\xenko\sources\core\Xenko.Core.IO\CSC	1	Active

Near the bottom of the error list, I see some different ones like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MC3074	The tag 'ModalWindow' does not exist in XML namespace 'http://schemas.xenko.com/xaml/presentation'. Line 1 Position 17.	Xenko.GameStudio	D:\Phr00tsSoftware\XenkoSource\xenko\sources\editor\Xenko.GameStudio\View\AboutPage.xaml	1	

Also, thank you for your response.

**Comment by phr00t** [comment]
I downloaded the latest Windows 10 SDK (probably should list that as a prerequisite) & "Retargeted Solution" to upgrade the project to the Windows 10 SDK I downloaded. Unfortunately, it doesn't seem to allow me to build the project & I still get tons of these errors:

103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\presentation\Xenko.Core.Presentation.Quantum\bin\Debug\net472\Xenko.Core.Presentation.Quantum.dll' could not be found
103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\tools\Xenko.Core.ProjectTemplating\bin\Debug\net472\Xenko.Core.ProjectTemplating.dll' could not be found
103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\presentation\Xenko.Core.Quantum\bin\Debug\net472\Xenko.Core.Quantum.dll' could not be found
103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\core\Xenko.Core.Reflection\bin\Debug\net45\Xenko.Core.Reflection.dll' could not be found
103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\core\Xenko.Core.Serialization\bin\Debug\net45\Xenko.Core.Serialization.dll' could not be found
103>CSC : error CS0006: Metadata file 'D:\Phr00tsSoftware\XenkoSource\xenko\sources\shaders\Xenko.Core.Shaders\bin\Debug\net45\Xenko.Core.Shaders.dll' could not be found

**Comment by Kryptos-FR** [comment]
Open Visual Studio installer and under "Desktop development with C++" you should also check "Windows 10 SDK (10.0.17134.0)". It is a prerequisite.

@xen2 [README.md](https://github.com/xenko3d/xenko/blob/master/README.md) is a bit ambiguous as it lists "Windows 10 SDK (10.0.17134.0)" as an optional prerequisite for UWP but it is also needed for "Desktop development with C++". Or is it already supposed to work with a higher version such as "Windows 10 SDK (10.0.17763.0)"?

**Comment by phr00t** [comment]
Ahhh, that was an "optional" prerequisite. I wanted to build for "Windows" & didn't know that meant "UWP" was required.

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.17134.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

Looks like a project outside of Xenko is complaining about my Windows SDK version. I probably should just get that specific Windows 10 SDK...

**Comment by phr00t** [comment]
It built when I installed the correct version of the Windows 10 SDK! Thank you for your help. I do have some other questions (like I don't see Vulkan as an option under "Rendering" when starting a project..?) I suppose I'll ask those types of questions on the forum...

**Comment by xen2** [comment]
@Kryptos-FR Good point, if it is required for pure windows build it should be listed as well.
I thought I tested it on a clean VM, will check again (also optional default packages might have changed).

**Comment by Kryptos-FR** [comment]
> also optional default packages might have changed

I thought of that as well. To be safe, we should list everything even if there are currently always selected (could be a screenshot f the installer).
