### ISSUE TITLE
Linux Build Broken in Github Version

### ISSUE THREAD

**Issue by phr00t** [xenko3d/xenko#313]
**Release Type**: Github

**Version**: Latest clone as of Jan 6th

**Platform(s)**: Windows 10 x64

**Describe the bug**
Trying to build a Xenko project for Linux gives the following errors:

[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.Engine 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.Navigation 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.Particles 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.Physics 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.UI 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7.Linux\MyGame7.Linux.csproj(0,0)]: Warning:Package 'Xenko.Video 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.Engine 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.Navigation 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.Particles 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.Physics 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.UI 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[D:\Phr00tsSoftware\XenkoProjects\SpaceEscape\MyGame7\MyGame7\MyGame7.csproj(0,0)]: Warning:Package 'Xenko.Video 3.1.0.1-beta01' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
[BasicCameraController.cs(3,18)]: Error:The type or namespace name 'Mathematics' does not exist in the namespace 'Xenko.Core' (are you missing an assembly reference?)
[BasicCameraController.cs(5,13)]: Error:The type or namespace name 'Input' does not exist in the namespace 'Xenko' (are you missing an assembly reference?)
[BasicCameraController.cs(25,16)]: Error:The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(27,16)]: Error:The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(31,16)]: Error:The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(33,16)]: Error:The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(35,16)]: Error:The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(18,44)]: Error:The name 'MathUtil' does not exist in the current context
[BasicCameraController.cs(20,17)]: Error:The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)
[BasicCameraController.cs(21,17)]: Error:The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)

**To Reproduce**
1. Build Xenko from current source
2. Run Xenko.GameStudio.exe
3. Start a new, general project
4. Select Linux as a target
5. Select Linux as the current project
6. Attempt build

**Expected behavior**
Linux able to build without errors.

**Additional context**
This same problem does NOT happen with the current 3.1 beta "0318" release from the official, public installer. There was a regression somewhere since then in the github source.

**Comment by Kryptos-FR** [comment]
You obviously need to build Xenko for Linux. Building the solution with default settings will only give you Windows binaries.

**Comment by phr00t** [comment]
Oh, _obviosuly_.
