### ISSUE TITLE
Material Transparency from Code - not working, or incorrect syntax/implementation?

### ISSUE THREAD

**Issue by Vhaldir** [xenko3d/xenko#316]
**Release Type**: Official Release/GitHub

**Version**: 3.1.0.1-beta01-0318

**Platform(s)**:
Windows

**Describe the bug**
material generated from code does not apply transparency - incorrect syntax/implementation?

**To Reproduce**
```
myModel.Materials.Add(new MaterialInstance(Content.Load<Material>("Materials/MatteBlack"))
{
	Material =
	{
		Descriptor = new MaterialDescriptor
		{
			Attributes =
			{
				Transparency = new MaterialTransparencyBlendFeature
				{
					Enabled = true,
					Alpha = new ComputeFloat(0.3f),
					Tint = new ComputeColor(Color.White)
				},
				CullMode = CullMode.Front
			}                                    
		}
	}
});
```

**Expected behavior**
Entity material should be partially transparent

Transparency works fine when adding the material from GameStudio.. not sure what I'm doing wrong here..

This is what I'm shooting for (screenshots when added from studio, NOT code):
![image](https://user-images.githubusercontent.com/542734/50878389-4fb2a380-138b-11e9-96a6-e4cd58dd2415.png)

![image](https://user-images.githubusercontent.com/542734/50878392-56d9b180-138b-11e9-9056-625d209718f4.png)

**Comment by Vhaldir** [comment]
Is this a bug, or am I missing something?

**Comment by xen2** [comment]
Did you find out?
I was going to point out you should use `Material.New(graphicsDevice, materialDescriptor)`.

**Comment by Vhaldir** [comment]
I've tried a few different approaches.. the transparency attribute wasn't the issue.. it's something to do with using a new Model() and then trying to apply meshes/textures/materials
