### ISSUE TITLE
Relative file path to resource incorrect in nuget

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#326]
**Release Type**:
Official 

**Version**: 
beta01-359

**Platform(s)**:
shared

**Describe the bug**
.xktex in assets contains incorrect relative path to resource file. the path is missing one "../" to get out of the 'Assets' folder and reach the 'Resources' folder.

**To Reproduce**
1. add a texture to a xenko package in a sub folder of 'Assets' and build the nuget via 'Pack' command in visual studio
2. add the produced nuget to a game project and inspect the assets of the package in game studio

**Expected behavior**
resource file should be found in installed nuget package

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/51358858-74aec100-1ac5-11e9-8022-1ae6f6e1ea9e.png)
![image](https://user-images.githubusercontent.com/1094716/51359077-5bf2db00-1ac6-11e9-9889-a5f5c0de517a.png)

**Log and callstacks**

**Additional context**
trying to build a re-usable xenko package

**Comment by xen2** [comment]
Thanks for the report.
There is some logic to supposedly deal with fixing path (https://github.com/xenko3d/xenko/blob/51ff4ead560002119a0d588c659759ef747bf160/sources/assets/Xenko.Core.Assets.CompilerApp/Tasks/PackAssets.cs#L133) but it's obviously wrong.

**Comment by tebjan** [comment]
looks not too complicated to fix. is it possible to debug the PackAssets task? if so, is this the way to go? https://blogs.msdn.microsoft.com/msbuild/2005/09/28/how-to-debug-a-custom-msbuild-task-using-visual-studio/

**Comment by xen2** [comment]
Yes, just debug the MSBuild.exe command with proper parameters, and put a breakpoint in PackAssets.cs

**Comment by tebjan** [comment]
great, thanks for the fix!
