### ISSUE TITLE
dotnet publish doesn't copy proper native/xenko dependencies

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#331]
**Release Type**: GitHub

**Version**: master

**Describe the bug**
Running `dotnet publish`  does not properly copy dependencies.
It seems `dotnet publish` uses slightly different targets than what's done for standard build.
(note: heard it might be unified in .NET Core 3.0)

**To Reproduce**
1. Create a new game with Linux or macOS
2. Build Linux or macOS (might be optional)
3. Run `dotnet publish`

**Expected behavior**
`Bin\Linux\Debug\linux-x64\publish` should contain all the native files (that are pulled by .ssdeps) just like in `Bin\Linux\Debug\linux-x64` but it doesnt.

The fix likely needs to be done in https://github.com/xenko3d/xenko/blob/master/sources/core/Xenko.Core/build/Xenko.Core.targets

**Comment by xen2** [comment]
I think we need a target with `AfterTargets="Publish"`, but not so sure on that.

**Comment by jazzay** [comment]
@xen2 for the build step (optional) are you doing that via **dotnet build**?

**Comment by xen2** [comment]
I did it with VS.
Didn't try `dotnet build`, does it work?

**Comment by jazzay** [comment]
Not sure, did not try yet. Probably publish is similar to dotnet build, so discrepancy might be between VS and dotnet?

**Comment by xen2** [comment]
I think `dotnet build` is OK and discrepency is between `dotnet build` and `dotnet publish`, but please double check.

**Comment by jazzay** [comment]
Explicitly adding this reference to the Windows project fixes the problems above:
```
    <PackageReference Include="Xenko" Version="3.1.0.1-beta01" PrivateAssets="contentfiles;analyzers" />
```
Which makes sense I guess since that Project is where the runtime.json file is. And now I see that the MacOS project contains that already.

**Comment by jazzay** [comment]
If I try to run a Windows published build from cmd line i get this:
```
D:\dev\gamedev\Xenko.TestProjects\TestMacPublishBug\Bin\Windows\Release\win-x64\publish
λ TestMacPublishBug.Windows.exe

Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Xenko.Rendering.BackgroundCubemapShaderKeys' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Xenko.Core.Native.NativeInvoke' threw an exception. ---> System.InvalidOperationException: Could not load native library libcore.dll from path [D:\dev\gamedev\Xenko.TestProjects\TestMacPublishBug\Bin\Windows\Release\win-x64\publish\x64\libcore.dll] using CPU architecture x64.
   at Xenko.Core.NativeLibrary.PreloadLibrary(String libraryName, Type owner)
   at Xenko.Core.Native.NativeInvoke..cctor()
```

**Comment by jazzay** [comment]
Adding this fixes the missing native libs as you suggested:
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
However when I run the published exe I now get a black screen. Looking inside the data/db child folder there are no actualy files located there.

**Comment by jazzay** [comment]
I have a solution for this will submit a PR.
