### ISSUE TITLE
Fix build instructions

### ISSUE THREAD

**Issue by DiegoBM** [xenko3d/xenko#337]
At the moment, build instructions as they are in the master branch won't successfully build.
If you follow the instructions from a clean clone, when opening Xenko.sln it will start on "Xenko.GameStudio" as startup project, so if you just build as indicated in the README, it will fail for most projects. You actually need to change the startup project to "Xenko", build that one, and then you'll be able to successfully build "Xenko.GameStudio"

**Comment by Kryptos-FR** [comment]
Not sure to get your point. If you follow the instructions, you will build the whole solution, so the startup project doesn't really matter.

**Comment by DiegoBM** [comment]
Please feel free to give it a try.
Clone the repository into a new folder, open build\Xenko.sln, and finally click Build -> Build Solution.

My results:
...
102>Done building project "Xenko.Samples.Tests.csproj" -- FAILED.
========== Build: 1 succeeded, 102 failed, 0 up-to-date, 0 skipped ==========

If I switch startup project to Xenko, and build that one, everything runs smoothly. Then I can build Xenko.GameStudio without any problem

**Comment by xen2** [comment]
Sounds like the issue is more about second build works better than first build (independent of startup project).
Can you please send us a log of the first (failing) build?

**Comment by DiegoBM** [comment]
Thank you @xen2, in my case it will fail regardless of how many consecutive times I click Build -> Build Solution as long as I don't change the startup project (or maybe there is another reason but changing it works for me). I'm sending you attached three consecutive build logs (I've diffed them and they are different but I presume it could be generation order or any other reason)

Note: The third attempt seems to have built many more projects but still 6 failures
[build-log.txt](https://github.com/xenko3d/xenko/files/2783332/build-log.txt)
[build-log-2.txt](https://github.com/xenko3d/xenko/files/2783333/build-log-2.txt)
[build-log-3.txt](https://github.com/xenko3d/xenko/files/2783335/build-log-3.txt)

**Comment by Kryptos-FR** [comment]
@DiegoBM Changing the startup project doesn't affect the build if you then select to build a particular project. The step to change the startup project is not needed.

There seems to be an issue with project build order, though. Trying to get more logs to know why.

**Comment by xen2** [comment]
It looks like package are still restoring. Could be a timing issue, might need to wait a while until it works? (don't think I had that recently, VS was restoring package before trying to build).
Also those CL.exe/LINK.exe missing errors are really weird.

**Comment by DiegoBM** [comment]
You guys are correct in that it's not related to switching to Xenko, since I've just tried and switched immediately from a clean clone to Xenko, and building also triggers some errors. It must be a timing issue as you mentioned @xen2

**Comment by xen2** [comment]
Also, does building or running current project (which should be Game Studio) works rather than Build Solution?

**Comment by DiegoBM** [comment]
If you mean clicking the Green Play button immediately after Visual Studio switches to ready, it does also fail from a clean clone (I have several of them, running multiple tests here hehe)

**Comment by Kryptos-FR** [comment]
I found the root issue: there is a resource contention to access the C++ linker (see error with link.exe in the log).

Possible workarounds:
* change the settings in VS to only build one project at a time
* build Xenko.Core first and only, then build the solution
* spread the build of the few C++ projects far from each other in the build order (esp. Irony vs Xenko.Core)

**Comment by xen2** [comment]
I likely culprit is `Xenko.Native.targets` calling another `.sln` (which doesn't work well when called multiple time at the same time, maybe writing same files or something).
I will investigate tomorrow.

**Comment by DiegoBM** [comment]
Thank you @Kryptos-FR, I've found that if after opening a new clone I wait for like 5 or 6 minutes (even though it says "Ready", it seems to be doing a background live code analysis and the package manager seems to be working in the background as well even though there is no visual indication of it), it will display a few nugget errors and finally it will display a finished message. After that I seem to be able to build the default project without issues (beyond few warnings)

Output from "Package Manager" section of the Output bar after 4-5 minutes (approx) of opening the project:

Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Samples.Templates could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Samples.Templates could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Samples.Templates could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Core.BuildEngine.Common could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Games.Testing could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Games.Testing could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Xenko.Input could not be loaded.
Time Elapsed: 00:00:17.6495128
========== Finished ==========

**Comment by xen2** [comment]
Can you try again with latest master and reopen if you still have issues?
I fixed the missing link.exe/cl.exe, but you might still have issues with restore.
Don't think I can do much about the restore (but hopefully you won't need to wait 4-5 min for that one, just a few seconds)

**Comment by DiegoBM** [comment]
@xen2 I tried again with similar results, 22 success and 80 failures on first build (there is improvement though), after giving it some time (to fetch dependencies I presume) it will just build normally. In any case I'll leave it closed and leave it to your judgement to decide the extent of this and whether or not is worth mentioning it in the build steps (maybe it's me the only person going through this?)

**Comment by xen2** [comment]
Could you share the new log to see if the cl.exe/link.exe missing errors are gone at least?

**Comment by DiegoBM** [comment]
I sure can
[build-log.txt](https://github.com/xenko3d/xenko/files/2788501/build-log.txt)
