### ISSUE TITLE
Update to latest SharpDX

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#34]
Should be easy and makes xenko engine compatible to other projects using latest SharpDX already.

**Comment by tebjan** [comment]
when i wrote this issue i was under the impression that xenko was still using sharpdx 3.2 but xenko 3.0 is using sharpdx 4.0.1 which is fairly new. so not a high priority issue, probably..

**Comment by Line-** [comment]
This should be probably be closed, there isn't a stable release past 4.0.1 that we would want to update to until 4.2.0 is released.

**Comment by Kryptos-FR** [comment]
@Line- It's fine to close the pull request. But we can keep that issue open until a new stable version is released. It shows that we had a discussion and hence would prevent people from creating duplicates.

**Comment by xen2** [comment]
Updated to SharpDX 4.2.0 in latest 3.1 beta (will be released in few minutes)
