### ISSUE TITLE
An Android Error

### ISSUE THREAD

**Issue by Cafory** [xenko3d/xenko#341]
> **Release Type:**
> Official
> 
> **Version:**
> 3.0.0.6 Official
> Launcher 3.0.5
> 
> **System:**
> Windows 10
>
> 
> Graphics Chipset
> AMD Radeon HD 7700 Series
> Memory Size 1024 MB
> Radeon Software Version 17.4.4
> 
> **Describe the bug**
>The required parameter "Android Sdk Directory" for the task "Get Java Platform Jar" was not assigned.

How can I reslove thic error?

**Comment by xen2** [comment]
Can you create a simple (non-Xenko) Android project in Visual Studio and see if it works?

**Comment by pikachuk** [comment]
try to install the android support from visual studio installer, it could fix it

**Comment by xen2** [comment]
VS issue and no recent update, closing.
