### ISSUE TITLE
Audible clicks at the end of sound effects

### ISSUE THREAD

**Issue by SoulRider** [xenko3d/xenko#350]
**Release Type**: Official Release

**Version**: 3.0.0.7

**Platform(s)**: Windows, other platforms not tested

**Describe the bug**
Sound effects have a click at the end of the clip, audio fine on builds in 3.0.0.6, only occurs on builds in 3.0.0.7.

**To Reproduce**
1. Add a sound effect with a short wav (1s length)
2. Build project, deploy and programmatically play the sound.
3. The sound will click when it reaches the end

**Expected behavior**
The sound to play without clicking.

**Screenshots**
N/A

**Log and callstacks**
N/A

**Additional context**
I've tried reimporting the audio, setting the compressionRatio to 1, and still the issue occurs.  I can't record audio of the difference to submit, but I do have two version of my project, one built in 3.0.0.6 with good audio and the following built in 3.0.0.7 with the click issue.

The tiny example demos however are each over the 10mb limit of this platform.  I can be contacted on discord to supply them via an alternative method.  They come to a combined 57mb.

This is possibly related to the previously closed android audio issue of which I copied most of this issue log:
https://github.com/xenko3d/xenko/issues/235

**Comment by guygodin** [comment]
I am still experiencing the same issue with clicks at the end of sounds with 3.0.0.8 on Android FYI

**Comment by ryancheung** [comment]
I've got the same issue. @xen2 could u have the spare time to fix this?
