### ISSUE TITLE
Recent master-3.0 branch builds but GameStudio exits without window display.

### ISSUE THREAD

**Issue by aurodev** [xenko3d/xenko#352]
**Release Type:**
Development

**Version:**
3.0.0.7-Dev Latest (1.26.2019)
3.0.0.7-Dev Older (1.24.2019)

**Platform(s):**
Windows 8.1

**System**
OS/device including version:
Windows 8.1 64bit, 8GB AMD FX 6350 6 core
.NET framework installed as of 1.21.19 .NET 4.7.2 Reg key: Release REG_DWORD 461814
Nuget 4.92

Graphics Chipset
AMD Radeon HD 7700 Series
Memory Size 1024 MB
Radeon Software Version 17.4.4

**Describe the bug**
The latest, 1.26.2019, master-3.0 branch builds, runs and exits without displaying a window.
Under the VS2017 debugger it has Nuget, mscorlib and other errors, see **debugger_3.0.0.7_1.26.9.txt**

A 1.24.2019 master-3.0 clone builds and runs successfully.

The latest (1.26.2019) master-3.0 GameStudio
- builds successfully
- deletes contents of C:\Users\Greg\.nuget\packages\xenko
- shuts down without displaying a window or an error.
- debugger: Exits with an Invalid Operation error in mscorlib etc.

The older (1.24.2019) master-3.0 Gamestudio
- builds successfully
- writes the contents of C:\Users\Greg\.nuget\packages\xenko
- runs successfully

**To Reproduce**
1. clone the master-3.0 branch
2. Debug build 
3. Run Xenko.GameStudio.exe

**Expected behavior**
GameStudio runs without errors.

**Screenshots**
**master-3.0 from 1.24.2019**
![nuget packages xenko](https://user-images.githubusercontent.com/7356383/51864158-f1853a80-2310-11e9-8b5e-59324a312897.PNG)

**Git history for master-3.0 1.24 and 1.26**
![gitgui1](https://user-images.githubusercontent.com/7356383/51864287-5476d180-2311-11e9-9555-377ba744af76.PNG)

**Package sources for master-3.0 from 1.26.2019**  _same behavior when all local sources are deleted_
![packagesources_latest_master3 0 0 7](https://user-images.githubusercontent.com/7356383/51864406-b20b1e00-2311-11e9-914a-6af3a8419d50.PNG)

**Log and callstacks**
Debug run of Gamestudio from master-3.0 1.26.2019
[debugger_3.0.0.7_1.26.19.txt](https://github.com/xenko3d/xenko/files/2804808/debugger_3.0.0.7_1.26.19.txt)

**Additional context**
Not a critical project issue for us, just a bug hunt.

**Comment by aurodev** [comment]
**Update**
After deleting everything in 2 nuget directories  **master-3.0 1.26.2019** runs and writes the packages.
**\AppData\Local\Xenko\NugetDev**
**\.nuget\packages\xenko**

_Version conflict?_  It checked for the presence of the nugets, saw they existed from the other version so it left them alone?

A mini build guide pointing out some of this might help people new to these issues.  The more people that can build Xenko @ home the more stuff gets worked on.  ;)

@Kryptos-FR

**Comment by xen2** [comment]
Yes it looks like your Xenko.3.0.0.7-dev.nupkg was corrupt (probably process was stopped while writing it the previous time?).
3.1 works differently so it shouldn't happen anymore.

**Comment by xen2** [comment]
Thanks for the investigation.
