### ISSUE TITLE
Rigidbody component collapses in the property grid after Ctrl+S (File >> Save) is pressed

### ISSUE THREAD

**Issue by crystalboxes** [xenko3d/xenko#358]
**Release Type**: GitHub

**Version**: 3.1.0.1-beta01

**Platform(s)**: Windows

**To Reproduce**
1. Add a Rigidbody component to the entity, expand it properties in the property grid.
2. Press Ctrl+S. 

**Expected behavior**
It collapses and doesn't remember it's "expanded" state.

This is a huge workflow killer, this component has many parameters to tweak. After pressing "build the project and start the game button", the scene will be inevitably saved and all rigid body component properties will collapse. 

**This doesn't apply only for rigid body component.** Many components, like particle system have a lot of nested properties. When typically working with it, the property grid becomes long and ideally you want to have the vertical scroll bar state preserved after save/game launch, so you could go back later and quickly adjust a specific particle system parameter.

**Comment by tebjan** [comment]
i agree, this happens for most property inspectors. i noticed it for particle systems, which also has a deep structure. @Kryptos-FR any idea where in the code this can be fixed? i know that there are some attributes for properties, but it think during runtime the user state should never be changed, i a component is expanded it should stay this way, at least until game studio is closed, doesn't need to be saved.

**Comment by profan** [comment]
This is also painful for anything related to UI, where you when going between elements are constantly reopening the same submenus in the property grid and it slows down an already slow workflow quite a lot.

![annoying menus](http://odin.prfn.se/u/2019-08-17_20-16-16.gif)
