### ISSUE TITLE
Link working 

### ISSUE THREAD

**Issue by jpumph029** [xenko3d/xenko#361]
**Release Type**: 
ContributorLicenseAgreement.md

**Platform(s)**: 
Github
**Describe the bug**
Link is not working @: "https://xenko.com/features/licensing/"
**To Reproduce**
Go to : https://github.com/xenko3d/xenko
Navigate to: https://github.com/xenko3d/xenko/blob/master/README.md
Click on: this link https://xenko.com/features/licensing/

**Expected behavior**
Works

**Comment by xen2** [comment]
Thanks for the report, fixed in https://github.com/xenko3d/xenko/commit/5d91b9cf56ce416813aff77162f7d6e33a840f52
