### ISSUE TITLE
Two different classes have the same DataContract Alias

### ISSUE THREAD

**Issue by azeno** [xenko3d/xenko#369]
**Release Type**: GitHub

**Version**: 3.1.0.1-beta01-0438+g5f596657

**Platform(s)**: Windows

**Describe the bug**
The asset compiler causes a type load exception and build fails.

Our setup looks like this from top down:
TestGame.Windows -> TestGame
TestGame.Windows -> VL.Xenko.Integration -> VL.Xenko.EffectLib -> VL.Xenko

VL.Xenko contains a custom render feature we call `LayerRenderFeature` which uses a custom component called `LayerComponent` which is attributed with `[DataContract(nameof(LayerComponent))]`. The LayerRenderFeature was added to the graphics compositer and from then on the build fails with a type load exception: `System.TypeInitializationException: Der Typeninitialisierer für "<Module>" hat eine Ausnahme verursacht. ---> System.InvalidOperationException: Two different classes have the same DataContract Alias [LayerComponent]: VL.Xenko.Rendering.LayerComponent and VL.Xenko.Rendering.LayerComponent`

**To Reproduce**
I can give you access to the private repo if build log and above description is not enough.
An even simpler example is in the following zip file, just compile MyGame.Windows
[MyGame2.zip](https://github.com/xenko3d/xenko/files/2841551/MyGame2.zip)

**Log and callstacks**
[buildlog.txt](https://github.com/xenko3d/xenko/files/2841053/buildlog.txt)

**Comment by tebjan** [comment]
@azeno don't we have even two render features in that dependency (one older we don't use anymore)? but could be a hint..

**Comment by azeno** [comment]
It's not about the render feature, see my attached zip file.

**Comment by xen2** [comment]
Fixed with feb297a8
