### ISSUE TITLE
[GameStudio] Can't close c# tab

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#373]
**Release Type**:
official

**Version**: 
beta01-0441

**Platform(s)**: 
windows

**Describe the bug**
c# tabs connot be closed, there is no 'x' and the context menu doesn't have a close option. not even 'close all' does anything.

**To Reproduce**
1. double click a c# file in the asset view

**Expected behavior**
normal tab behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/52644451-21bb0480-2edf-11e9-880c-8a850f5e10de.png)

**Comment by tebjan** [comment]
looks like #286

**Comment by xen2** [comment]
Does it happen on a specific project (could be because dock layout is serialized without the `CanClose`) or also on new projects?

**Comment by tebjan** [comment]
confirmed the project was saved with an older beta, a newly created project doesn't have this issue. might be low prio... do you know how to fix it in the project files? for me this would suffice as a fix.

**Comment by xen2** [comment]
Workaround:
* Open `%AppData%\Xenko\GameStudioInternal.conf`
* Delete the `DockingLayout` and `DockingLayoutEditors` for your project.

**Comment by tebjan** [comment]
yes, this works. would it make problems to delete the entire file?

**Comment by Kryptos-FR** [comment]
@tebjan no. It will recreate the file with default values the next time you open the Game Studio.
