### ISSUE TITLE
SyncScript Inheritance hiding base class member with "new" keyword broken.

### ISSUE THREAD

**Issue by DevJarmo** [xenko3d/xenko#374]
**Release Type**: Official Release
**Version**: 3.0.0.6 (or .7)
**Platform(s)**: Windows

**Describe the bug**
When implementing SyncScript on a base class, a child class using "new" keyword to hide base class fields does not hide/overwrite the base fields at runtime.  This could be due to integration with Game Studio. I am able to cache references/propagate fields for the child script in Game Studio but at runtime base class fields are null. 

You can work around this by assigning base fields to child fields during Start().

**To Reproduce**
1. Create a base SyncScript (i.e. "Character").
2. Create a child class and inherit from base (i.e. "Ninja : Character").
3. Create protected or public fields/properties in Character.
4. Create public fields/properties in Ninja (use the "new" keyword).
5. Cache references in Game Studio (assign a prefab to field/property in Ninja).
6. Compile and run.

**Expected behavior**
I would expect this to work, but I'm fairly amateur and could be missing something. I would expect Script components to support inheritance and still be able to cache references through Game Studio.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
Unfortunately I moved on and have no screenshots, there are no errors though, just null base class members.

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**
In a large game I would expect script components would support inheritance and there would be modularity in inheritance and interfaces, etc.

**Comment by Kryptos-FR** [comment]
It is not a bug in Xenko, just how c# works. using the `new` keyword on members is bad and just be avoided at all cost.

The `new` keyword only hides the members in the context of that class, not from the base class point of view.

**Comment by DevJarmo** [comment]
Awesome, thanks. I don’t generally use the feature and misunderstood it’s implementstion.

**Comment by Kryptos-FR** [comment]
Welcome.
It's by doing mistake that we learn. You are on the right track.
