### ISSUE TITLE
[Math] Quaternion expects left handed coordinate system

### ISSUE THREAD

**Issue by Eideren** [xenko3d/xenko#378]
**Release Type**: Any.

**Version**: Latest as of the time of writing.

**Platform(s)**: Any.

**Describe the bug**
Xenko uses a right handed coordinate system(right < 0) while Quaternions expects a left handed one(right > 0), this leads to the issue described below.

What v should logically be equal to, given xenko's coordinate system, is a vector pointing downwards, but it returns a vector pointing upwards instead.
```
var right = new Vector3(-1f, 0f, 0f);
var forward = new Vector3(0f, 0f, 1f);
var deg90AsRad = 1.570796f;
var cw90Degrees = Quaternion.RotationAxis(right, deg90AsRad);
var v = Vector3.Transform(forward, cw90Degrees);
```
Well, good luck to whoever decides to fix that one !

**Comment by tebjan** [comment]
> Xenko uses a right handed coordinate system (right < 0) while Quaternions expects a left handed one (right > 0), this leads to the issue described below.

this is technically not the right way to describe handedness. left/right handed is not (only) about the x-axis, it describes how the positive direction of the basis vectors of a coordinate system are related to each other.

the convention in xenko is:
right -> positive x
up -> positive y
forward -> negative z

which is indeed right handed.

so this assumption is incorrect:
`> var right = new Vector3(-1f, 0f, 0f);`

your camera might look into the opposite direction...

see also slide 13-16 in this presentation:
https://docs.google.com/presentation/d/14rxW-qZ0ZwDIppdc_4uGGYc_Fdm10NbYLMXOKGZ-BCg/

**Comment by Eideren** [comment]
Thank you for clarifying this, I should have know. I got too caught up be my own code to think this through !

**Comment by tebjan** [comment]
always fun to propagate knowledge. this topic is one of the most confusing in 3d engines and i never get tired to help anyone with it. happy coding!
