### ISSUE TITLE
AudioSystem not working on Android 64-bit

### ISSUE THREAD

**Issue by guygodin** [xenko3d/xenko#379]
**Release Type**: Official Release/GitHub (please choose appropriate option)
GitHub

**Version**: Version number and/or git branch
3.0.0.4

**Platform(s)**: Does the problem occur on Windows, Android...?
Android

**Describe the bug**
I've reported this in the old SiliconStudio issues section but wanted to get it submitted as an issue here. I get a DllNotFoundException in AudioLayer.Init() when trying to initialize the AudioSystem. I think the error originates from here:

D/Mono ( 3009): DllImport error loading library ‘libxenkoaudio.so’: 'dlopen failed: cannot locate symbol “_Unwind_SetGR”

Works without issues with armeabi-v7a builds.

Is this a known limitation or can it be fixed to work with 64bit builds?

**To Reproduce**
1. Create an AudioSystem
2. initialize it

**Expected behavior**
It should work with 64-bit builds like it does with 32-bit builds

**Comment by xen2** [comment]
Thanks for the report.
I don't know if it failed since beginning or only at some point.

It says you tried GitHub but 3.0.0.4?

Latest master contains a bump from LLVM 5 to 7, wondering if by chance it could help.
Otherwise it will need further investigation.

**Comment by guygodin** [comment]
It has been failing ever since I started using Xenko (before it switched to MIT license). I will need to merge the latest changes and give the latest code a try. Will update this issue once I do so.

**Comment by guygodin** [comment]
The Xenko.Android solution doesn't build correctly with the latest master branch: it just skips every project =/

**Comment by guygodin** [comment]
I've manually merged the LLVM update (and updated to 3.0.0.8 as its the last version that compiles properly on Android) but still experience the same crash with arm64-v8a:

03-05 15:41:41.922: E/VRD(989): System.TypeInitializationException: The type initializer for 'Xenko.Audio.AudioEngine' threw an exception. ---> System.DllNotFoundException: libxenkoaudio
03-05 15:41:41.922: E/VRD(989):   at (wrapper managed-to-native) Xenko.Audio.AudioLayer.Init()
03-05 15:41:41.922: E/VRD(989):   at Xenko.Audio.AudioEngine..cctor () <0x7f593c0500 + 0x0002f> in <21455326a0234cd5ab6bc7ee54f4c28f>:0 
03-05 15:41:41.922: E/VRD(989):    --- End of inner exception stack trace ---
03-05 15:41:41.922: E/VRD(989):   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
03-05 15:41:41.922: E/VRD(989):   at Xenko.Audio.AudioEngineFactory.NewAudioEngine (Xenko.Audio.AudioDevice device, Xenko.Audio.AudioLayer+DeviceFlags deviceFlags) <0x7f593b9404 + 0x00033> in <21455326a0234cd5ab6bc7ee54f4c28f>:0 
03-05 15:41:41.922: E/VRD(989):   at Xenko.Audio.AudioSystem.Initialize () <0x7f594ad3d0 + 0x0012f> in <3158c84f01f94be4920c7b032aea7b0a>:0

**Comment by xen2** [comment]
The file is actually there and it is still related to `D/Mono ( 3009): DllImport error loading library ‘libxenkoaudio.so’: 'dlopen failed: cannot locate symbol “_Unwind_SetGR”`, right?

**Comment by guygodin** [comment]
Correct
