### ISSUE TITLE
Spritesheets not editable from GameStudio

### ISSUE THREAD

**Issue by Chris3606** [xenko3d/xenko#38]
In version 3.0.0.1, after importing a png of a SpriteSheet, I can't open the SpriteSheet editor without manually editing the xksheet file.  I tried both double-clicking the sprite, and right-clicking - edit asset.

Is this a bug, or are the docs out of date on how sprites work?

**Comment by jayrulez** [comment]
I will need to check all embedded resources for similar issues.
