### ISSUE TITLE
Int3 as component property causes GS to crash

### ISSUE THREAD

**Issue by boriscallens** [xenko3d/xenko#383]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta01-0441

**Platform(s)**: Windows

**Describe the bug**
Adding a component property of the type Xenko.Core.Mathematics.Int3 causes Game Studio to crash with a confusing exception log upon attaching to any entity.

**To Reproduce**
Repro here: https://github.com/boriscallens/XenkoBuildRepro

1. Create a default game
2. Create a basic component
    [DataContract("MyComponent")]
    public class MyComponent: EntityComponent
    {
      // public Vector3 Working { get; set; } 
      public Int3 Crashing { get; set; }
    }
3. Attach the component to any entity in the default scene in Game Studio

**Expected behavior**
The component is added to the entity and a Crashing property of the type int3 is editable on the component.
Alternatively/complementary a helpful error message and placeholder Unloadable component. Keeping GS functional for editing.
Alternatively a more helpful exception / stacktrace

**Screenshots**
N/A

**Log and callstacks**
[buildLog.txt](https://github.com/xenko3d/xenko/files/2873111/buildLog.txt)

**Additional context**
Maybe it has nothing to do with the type, but with the editor ui component?  
That would explain the stacktrace pointing to XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.  
From comparing the Int3 implementation with the Vector3 implementation I couldn't identify any relevant differences.

**Comment by Kryptos-FR** [comment]
The crash in Xaml UIElement probably means the template for the editor of `Int3` has some issues.

If someone wants to investigate, the culprit could be in file https://github.com/xenko3d/xenko/blob/master/sources/presentation/Xenko.Core.Presentation/Themes/ExpressionDark/Theme.xaml#L4199 (at least that's a good starting point).

**Comment by dfkeenan** [comment]
Not sure if this is a problem but the `Int<X>Editor`s don't override the default style key where as all the `Vector<X>Editor`s do. i.e. https://github.com/xenko3d/xenko/blob/master/sources/presentation/Xenko.Core.Presentation/Controls/Vector3Editor.cs#L32

**Comment by Kryptos-FR** [comment]
To help investigate property grid issues, we have that test asset that can be used: https://github.com/xenko3d/xenko/blob/master/sources/editor/Xenko.Assets.Presentation/Test/TestAsset.cs

Note that it currently doesn't include `IntX` properties, which could be a good addition.

**Comment by dfkeenan** [comment]
There is an extra `/>` on line 4229 of that theme file.

https://github.com/xenko3d/xenko/blob/f56d4f836098f0c9fd5a39eeebffa2d7ed59a179/sources/presentation/Xenko.Core.Presentation/Themes/ExpressionDark/Theme.xaml#L4229

**Comment by boriscallens** [comment]
Do fixes to Game Studio also get pushed through nuget somehow or is this a more involved process?
