### ISSUE TITLE
Typing the name of an incompatible asset type in a property editor field causes a crash.

### ISSUE THREAD

**Issue by dfkeenan** [xenko3d/xenko#393]
**Release Type**: Official Release & GitHub

**Version**: >= 3.0 (Possibly all)

**Platform(s)**: Windows?

**Describe the bug**
When typing the name of an asset in the text box of an asset property in the property inspector window that is of a different type than the one expected it causes a crash.

**To Reproduce**
1. Create a script with a property of type `Scene` Called "NextScene".
2. Add script to an entity.
3. Create a model asset called "Sphere".
4. Type the name "Sphere" in the textbox of the "NextScene" property.
5. CRASH

**Expected behavior**
It should handle it gracefully. The same way it does if you try to Drag and Drop an asset. Which sets the property to null.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**
The exception is thrown at https://github.com/xenko3d/xenko/blob/293d60a2bdc4b6d2773a1da914fd802483828288/sources/presentation/Xenko.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs#L538

It should possibly return null if it cannot convert it.  I tried this fix and it gave the expected behavior as above. I am not sure if this would cause any other issues though.

**Comment by profan** [comment]
Can confirm I ran into this just yesterday when pasting a color code into a box on a material property:
![image](https://user-images.githubusercontent.com/2816340/53297592-bf3bff80-3820-11e9-99a8-25652385e031.png)

(typing in an invalid property there, like just taking the same text and omitting the # causes a crash)

**Comment by profan** [comment]
Any idea @xen2 if solving this by returning null if it can't convert it would cause any far-reaching consequences?

Just ran into this again today:
![image](https://user-images.githubusercontent.com/2816340/57339960-1836e680-7134-11e9-80e4-34055157b790.png)

**Comment by xen2** [comment]
@profan Agree it definitely shouldn't crash the editor.
Maybe a better approach would be to display no editor (or an error message explaining it can't be edited, possibly with a button to get more details/actual exception).
That way we are still aware when it's broken, and editor shouldn't crash anymore.

**Comment by xen2** [comment]
@profan need to investigate if `null` has no side effect.
If it doesn't set the `null` value and stop right there, that's probably fine.
Also, some feedback would be good to have too (i.e. a tooltip that display the error message with some red color, just like when you enter invalid data in some web form).

**Comment by xen2** [comment]
To summarize: my feeling is that it's probably better not to change the converters themselves (which could fail converting, this could happen) but to properly handle failed conversion at https://github.com/xenko3d/xenko/blob/293d60a2bdc4b6d2773a1da914fd802483828288/sources/presentation/Xenko.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs#L538 (or somewhere more up the editor callstack).

Here's what the expected behavior could be:
- If possible, keep the invalid value in the editor (at least as long as it has focus, should we revert back if focus left?)
- Display an error tooltip with the exception message
  Website example:
  ![image](https://user-images.githubusercontent.com/527565/62296673-e0f47f00-b46f-11e9-9f6f-5126636c8ff6.png)

**Comment by DaveTheGameDev** [comment]
I have made a commit in my fork that has a basic fix for this issue by using null as stated above and exiting the SetNodeValue function early if it is null resulting in the value never actually getting set causing the editor UI and the value of the parameter to stay as it was.

https://github.com/DaveTheGameDev/xenko/commit/5789d1de5fea017018be15587344224c6021407c

I suggest changing the input from string type to a drop down with valid assets. 
(Change the select asset window to a drop down)

If we still want to be able to use a string as an input then i agree a tool tip saying what issue occurred  would also work

Here is a video of what my changes result in.
https://youtu.be/ZGQ03bpQXYE

**Comment by profan** [comment]
@DaveTheGameDev you can't really do only the dropdown with valid assets always, sometimes you want things like enter a hex code for a colour to just enter (quite common for me at least) And there are other places too where you have something like a numeric or string input where it's the same code path, where you also still can't do just a dropdown.

Personally I think just reverting it to the old value as with this change is fine at least, maybe adding a notification that shows up somewhere to say it's an error as in xen's second example?

**Comment by DaveTheGameDev** [comment]
@profan  Yeah i agree with that. We could still have the drop down for certain situations and always ignore invalid characters for string based input fields.
