### ISSUE TITLE
Version is Blender 2.8 beta for windows 64 bit. For some reason files saved in blender 2.8 can not save and show this error report "Cannot open file C:\untitled.blend@ for writing : Permission denied"

### ISSUE THREAD

**Issue by MichaelJ1423** [xenko3d/xenko#408]
**Release Type**: Official Release/GitHub (please choose appropriate option)

**Version**: Version number and/or git branch

**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by Kryptos-FR** [comment]
Closing because not respecting the template and doesn't seem to be related to Xenophobic at all.

**Comment by dfkeenan** [comment]
@Kryptos-FR , you have been burnt by autocomplete again. 😄

**Comment by Kryptos-FR** [comment]
Damn
