### ISSUE TITLE
Unable to edit material properties

### ISSUE THREAD

**Issue by mockc** [xenko3d/xenko#409]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta02-0532

**Platform(s)**: Windows 10 x64

**Describe the bug**
Unable to edit most material properties because the only option in the drop down list is "None". 

**To Reproduce**
1. In the "Asset View" pane click "Add Asset"
2. Select "Material" -> "Material" from the popup window
3. Make sure the new material is selected in the "Asset View" pane
4. Attempt to edit some of the material properties in the "Property grid" pane
5. Most properties display "None" as the only option.

**Expected behavior**
The material properties should be editable and allow options other than "None". For example, if you create a material using the "Diffuse material" asset template, the "Diffuse" property under "Shading" is pre-populated with "Diffuse Map". However, this option is unavailable when creating an empty material as describe in the steps to reproduce.

**Screenshots**
![Material](https://user-images.githubusercontent.com/20409842/54247170-491ce580-450e-11e9-9c1e-c48718ddc3bc.png)

**Log and callstacks**
N/A

**Additional context**
N/A

**Comment by Kryptos-FR** [comment]
Possibly caused by recent changes related to `Xenko.Rendering`.

**Comment by phr00t** [comment]
I can find other things to do in my current project, but quite a bit is held up due to this bug :(

**Comment by xen2** [comment]
OK I will take care of this one asap, sorry about that!
