### ISSUE TITLE
Unable to change light type

### ISSUE THREAD

**Issue by Rover656** [xenko3d/xenko#410]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta-02-0532

**Platform(s)**: Editor

**Describe the bug**
When configuring a light component, it is not possible to change the light type, the dropdown is simply empty.

**To Reproduce**
1. Create a new entity
2. Add a new light component
3. Attempt to change the light type

**Expected behavior**
The light type should be modifiable

**Comment by phr00t** [comment]
This is likely related to this issue: https://github.com/xenko3d/xenko/issues/409
