### ISSUE TITLE
Installation Еrror

### ISSUE THREAD

**Issue by kiridu1988** [xenko3d/xenko#414]
An error occurred while installing version 3.1.0.1-beta02-0539.
Failed to retrieve information about 'Xenko.SpriteStudio.Offline' from remote source 'https://api.nuget.org/v3-flatcontainer/xenko.spritestudio.offline/index.json'.
Unable to find package 'Xenko.Core.BuildEngine.Common.3.1.0.1-beta02-0539'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

An error occurred while installing version 3.1.0.1-beta02-0539.
Failed to download package 'Newtonsoft.Json.11.0.2' from 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg' has timed out after 100000ms.
Unable to find package 'Xenko.UI.3.1.0.1-beta02-0539'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

**Comment by kiridu1988** [comment]
"Visual Studio Installer" 85 KB/s downloading.

**Comment by kiridu1988** [comment]
I could not install Xenko and Visual Studio.

Why do we need Visual Studio?
And why do we need this launcher? It creates additional problems. Just delete it.

**Comment by Kryptos-FR** [comment]
> Why do we need Visual Studio?

We actually need MSBuild tools which is part of Visual Studio, but the whole Visual Studio installation is not required (while recommended).

> And why do we need this launcher?

For brand recognition, to show useful links and release notes, to manage all versions installed, etc.

> It creates additional problems. Just delete it.

No.

**Comment by kiridu1988** [comment]
Visual Studio has a commercial license.
And Xenko is Open Source.
Don't you think something is wrong here?

Yes, the launcher creates problems, proof of this in my first post.
Where can I just download the standalone distribution?

**Comment by Kryptos-FR** [comment]
> Visual Studio has a commercial license.
And Xenko is Open Source.
Don't you think something is wrong here?

Nothing wrong here.

> Where can I just download the standalone distribution?

Using the launcher :eyes:

Xenko is also distributed as nuget packages (see https://www.nuget.org/profiles/xenko.com). But since that seems to be the issue here, it won't help you. If your connection is slow, experiencing outage or network issues, there is nothing we can do on our end, unfortunately.

**Comment by kiridu1988** [comment]
Replace proprietary software with open source software.

The problems are not with my connection, but with your installer.

**Comment by kiridu1988** [comment]
And when will the Linux version appear?

**Comment by Kryptos-FR** [comment]
> The problems are not with my connection, but with your installer.

And a few lines above:
> "Visual Studio Installer" 85 KB/s downloading.

And also in your logs:
> The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg' has timed out after 100000ms.

> Replace proprietary software with open source software.

Is that an order? if you want people to fix issue in open-source project, I suggest you use a different tone. Remember that contributors work on their free time without receiving any income from it. 

> And when will the Linux version appear?

Xenko being an open-source project, you can also contribute yourself or sponsor further development through the Patreon link.

Finally, as with every project, decisions are made. They might not please everyone, but they are also the result of compromises. You can't expect to just come here and order people around. I'd suggest to also enter into contact with the community on our forums or discord channel and discuss your needs and/or vision of the project, in a civilized way.

**Comment by kiridu1988** [comment]
> without receiving any income from it.
> Patreon 

You contradict yourself.
I see no reason to continue this conversation.

And everything that you say is either your personal opinion, or obvious things, or completely absurd.
I am tired of this.

All the best.
