### ISSUE TITLE
Swapping "Visual Studio 2017 Build Tools" for "Microsoft.Build" from NuGet

### ISSUE THREAD

**Issue by DanielGilbert** [xenko3d/xenko#417]
**Is your feature request related to a problem? Please describe.**

While issue #414 went completely south in terms of communication, I noticed an interesting comment by @Kryptos-FR :
> We actually need MSBuild tools which is part of Visual Studio, but the whole Visual Studio installation is not required (while recommended).

I stumbled on this, because after Installing Visual Studio 2019 RC2, I cannot start GameStudio, neither can I build one of my projects. I "solved" this issue by switching to one of my machines that run Visual Studio 2017 only. The error is related to a missing dependency, "Microsoft.Build". After reading on this issue, I noticed that it comes up occasionally here and there, mostly after some Visual Studio updates.

So I switched to a new machine, without Visual Studio installed, and installed Xenko. I noticed that Xenko installs the "Visual Studio 2017 Build Tools". After reading on this issue, I wonder if we need the VS 2017 install at all, if we consider the solution below?

**Describe the solution you'd like**

If you read the "[Update an existing application for MSBuild 15](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2017#use-nuget-packages-preferred)" guide by Microsoft, you notice that they suggest (and actually prefer) referencing MSBuild as NuGet packages. By doing so, we could get rid of the Visual Studio 2017 dependency. Or did I miss something?

As far as I can tell, this might also help pushing #376 forward. However, if you've already investigated on this issue, feel free to close it. I couldn't find anything in this direction. :)

_(as this is my first issue here, I hope I did it okay-ish)_

**Comment by ryancheung** [comment]
I got the same problem when both installing Visual Studio 2019 RC and Visual Studio 2017.

**Comment by Kryptos-FR** [comment]
We already do that.

**Comment by DanielGilbert** [comment]
Thanks @ryancheung for the tip!

Also, thanks @Kryptos-FR for chiming in. I was looking for that PackageReference, but obviously didn't find it. 
Yes, updating them might be a good idea, as the release of the final version of VS 2019 is imminent, and support for MSBuild 16 is needed. According to [this commit](https://github.com/Microsoft/MSBuildLocator/commit/183c2cf2809830a93d8ed44ef8300348f9beac0a), support for MSBuild 16 got added around october 2018, which must be included in 1.1.2, I guess.

But that's not the scope of this issue, so I'll close it for now. Feel free to re-open if you would like to use it for tracking purpose. :)

Thanks folks!
