### ISSUE TITLE
Visual Studio Royalties

### ISSUE THREAD

**Issue by kiridu1988** [xenko3d/xenko#419]
Visual Studio is a paid product.

Xenko uses Visual Studio, so everyone must pay Microsoft royalties?

**Comment by jayrulez** [comment]
No, you do not need to pay royalties.

Also, please use the discord or forums for general questions like this and only open issues or feature requests here.

Regards.

**Comment by kiridu1988** [comment]
Do you have a law degree?

**Comment by Kryptos-FR** [comment]
Closing as non-sensical.

**Comment by kiridu1988** [comment]
It does not matter that in games there are no parts from Visual Studio and so on.

These things cannot be used for free during development in commercial projects.

**Comment by xen2** [comment]
@kiridu1988 Visual Studio is not mandatory. MSBuild is and can be installed for free.
If you don't like that, nobody forces you to use Xenko anyway.

PS: I consider this almost off topic for GitHub and will block if it keeps going.
Feel free to bring this to the (moderated) forums.

**Comment by kiridu1988** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/0daefd5d-8d5a-499c-bd16-c3e7aba68c4d/is-msbuild-free-for-commercial-use?forum=msbuild

**Comment by kiridu1988** [comment]
![image](https://user-images.githubusercontent.com/47792950/54941783-b84afe80-4f3e-11e9-8921-a380809f2de3.png)
and "Open in IDE"

Xenko requires Visual Studio to create and edit code.
Why is this problem still not solved?
Some people and companies may violate the license and they will not even know about it.
In addition, Microsoft may at any time change the license.
Replace the code editor with VS Code.

**Comment by tebjan** [comment]
Xenko has a built in c# code editor. why do you still think it depends on visual studio after two people who know the engine and work with it have told you that only msbuild is required?

**Comment by Kryptos-FR** [comment]
@kiridu1988 At some point if you fail to understand what we are telling you, there is nothing we can do anymore. Your own link shows that MSBuild doesn't require a license.

And to prove it further, its license is clearly MIT as can be seen here: https://github.com/Microsoft/msbuild/blob/master/LICENSE

And to finish of the screen shot you posted. Yes we do integrate with Visual Studio as a convenience if it is installed on the same machine. But being "compatible with" is not the same as "requiring". As of today, Xenko doesn't require Visual Studio and that statement won't change in the future.

**Comment by kiridu1988** [comment]
> 
> 
> Xenko has a built in c# code editor, visual studio is optional because many developer prefer it since its the tool they work with every day. why do you still think it depends on visual studio after two people who know the engine and work with it have told you that only msbuild is required?

https://www.gamefromscratch.com/post/2015/08/04/A-Closer-Look-At-Paradox3D.aspx
"The Coding Experience"

Did he add code to the project using Visual Studio?
How can I do this with the built-in code editor?

**Comment by Kryptos-FR** [comment]
@kiridu1988
1. the video your are linking are several years old.
2. Have you just tried once yourself? Literally double clicking on any script in the editor will open the built-in editor.
3. All information about VS licensing was available easily with simple Google search query.

So please before asking anything here, do a little research. Everyone here is working on their free time. We would prefer to answer real question rather that simple one that don't need our involvement at all because all information is readily available.

**Comment by tebjan** [comment]
follow this https://doc.xenko.com/latest/en/manual/scripts/create-a-script.html
then double click it.

**Comment by kiridu1988** [comment]
I understood all this before you wrote it all.
