### ISSUE TITLE
GameStudio: when creating a new game/samples, detection code for platforms is broken

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#42]
When creating a new game/samples or updating platforms, the wizard says the required components are not installed for iOS, Android and UWP, even if the appropriate programs/modules are installed.
This is because the detection code is pretty outdated and needs to be updated.

XenkoConfig.cs contains the code: 
https://github.com/xenko3d/xenko/blob/0669deabfe65a04f80041433420f0ace0ad5ca9a/sources/engine/Xenko.Assets/XenkoConfig.cs#L97

**Comment by xen2** [comment]
Additional note: best way now might be to check packages installed with Visual Studio.
We already have a small abstraction for that: `VisualStudioVersions.AvailableVisualStudioInstances` which contains `PackageVersions`. This lists the options selected by users during VS install.

**Comment by AirAKose** [comment]
@xen2  Should it only check your default IDE for the packages, or all available?

**Comment by xen2** [comment]
Unfortunately the Default IDE is defined in `Xenko.Core.Assets.Editor` so it can't be accessed from `XenkoConfig.cs`. So for now, I would say it's enough to detect if any IDE match.

Then we could later adjust the editor side to also follow same logic, by either:
- automatically use different IDE than default one if there is one better matching requirement?
- or at least displaying a warning saying there is a better IDE to choose (maybe better to avoid confusing user by launching a different instance than expected and he knows what to fix/reinstall)

**Comment by xen2** [comment]
Fixed by #48
