### ISSUE TITLE
Could not find a compatible version of MSBuild: File Not found

### ISSUE THREAD

**Issue by boriscallens** [xenko3d/xenko#420]
**Release Type**: Official Release
**Version**: 3.1.0.1-beta02-05432
**Platform(s)**: Windows 10

**Describe the bug**
When pressing the big red Start 3.1.0.1-beta02-05432 buttton in the xenko launcher a dialogue " Could not find a compatible version of MSBuild" prevents me from going any further. 

**To Reproduce**
1. Fresh machine install.
2. Installed and used successfuly for work VS17 (and vs2019 preview, vscode):
  - Visual Studio core editor
  - .NET desktop development
  - Universal Windows Platform development
  - ASP.NET and web development
  - Azure development
  - .NET Core cross-platform development
3. Installed Xenko from homepage (http://xenko.com/files/XenkoSetup.exe)
4. Launched Xenko Launcher
5. Pressed the big red button

**Expected behavior**
Xenko Game Editor launches

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
  > Could not find a compatible version of MSBuild.
  > Check that you have a valid installation with the required workloads, or go to
  > www.visualstudio.com/downloads to install a new one.
  > System.IO.FileNotFoundException: Could not load file or assembly
  > 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  > or one of its dependencies.
  > The system cannot find the file specified. File name: 
  > 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  > at Xenko.Core.Assets.PackageSessionPublicHelper.CheckMSBuildToolset()
  > at Xenko.GameStudio.Program.<Startup>d__12.MoveNext()
  > in D:\BuildAgent\work\8cafb933a54b01d0\sources\editor\Xenko.GameStudio\Program.cs:line 241
  > WRN: Assembly binding logging is turned OFF etc..

**Additional context**
The file version at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe is 15.9.21.664

Seemingly related issue: https://github.com/xenko3d/xenko/issues/47

**Comment by boriscallens** [comment]
Anything else I can test? Not sure how I can make a minimal reproduction. Maybe with a VM?

**Comment by erictuvesson** [comment]
I am getting the same issue when running the AssetCompiler.

```
2>info 0.023s: [AssetCompiler] BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path=F:\Projects\xenko\samples\Graphics\MaterialShader\Bin\Windows\Debug\data --build-path=F:\Projects\xenko\samples\Graphics\MaterialShader\MaterialShader.Windows\obj\xenko\assetbuild\data --package-file=F:\Projects\xenko\samples\Graphics\MaterialShader\MaterialShader.Windows\MaterialShader.Windows.csproj --log-pipe=
2>info 0.024s: [AssetCompiler] Starting builder.
2>EXEC : error 0.047s: [AssetCompiler] Could not find a compatible version of MSBuild.
2>
2>Check that you have a valid installation with the required workloads, or go to [www.visualstudio.com/downloads](https://www.visualstudio.com/downloads) to install a new one.
2>
2>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2>   at Xenko.Core.Assets.PackageSessionPublicHelper.CheckMSBuildToolset()
2>   at Xenko.Core.Assets.CompilerApp.PackageBuilder.BuildMaster()
2>
2>WRN: Assembly binding logging is turned OFF.
2>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
2>Note: There is some performance penalty associated with assembly bind failure logging.
2>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
2>
2>C:\Users\erict\.nuget\packages\xenko.core.assets.compilerapp\3.1.0.1-beta01-0313\build\Xenko.Core.Assets.CompilerApp.targets(68,5): error MSB3073: The command ""C:\Users\erict\.nuget\packages\xenko.core.assets.compilerapp\3.1.0.1-beta01-0313\build\..\lib\net472\Xenko.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path="F:\Projects\xenko\samples\Graphics\MaterialShader\Bin\Windows\Debug\data" --build-path="F:\Projects\xenko\samples\Graphics\MaterialShader\MaterialShader.Windows\obj\xenko\assetbuild\data" --package-file="F:\Projects\xenko\samples\Graphics\MaterialShader\MaterialShader.Windows\MaterialShader.Windows.csproj" --log-pipe=""" exited with code 1.
```

**Comment by myxibrium** [comment]
I am having the exact same issue. I'm not able to run Xenko or install the Visual Studio plugin.
