### ISSUE TITLE
Editor camera pan bug

### ISSUE THREAD

**Issue by DaveTheGameDev** [xenko3d/xenko#422]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Github
**Version**: Version number and/or git branch
 v3.1.0.1-beta2

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows Editor

**Describe the bug**
Camera panning in the editor does not take editor camera rotation into account. This causes the pan to ignore direction of mouse movement depending on direction facing to (left becomes right if you rotate the camera to face - on the x axis)

**To Reproduce**
1. Face direction so panning causes camera to move left when mouse is moved to the left.
2. Turn 180 degrees and pan to the left again and notice how your camera moves to the right (same direction as if you did not turn around at all)
3. Turn 90 degrees and now panning to the left causes the camera to move either forward or backwards.

**Expected behavior**
Panning to a direction with the mouse should pan in that direction  the mouse is moved

**Screenshots**
This screen shot moves the camera to the right if facing this direction and panning left with default editor settings
![image](https://user-images.githubusercontent.com/21057342/54897026-de5ea780-4f1a-11e9-9d48-7badeb5fb419.png)

**Additional Context**
Video showing the pan issue.
Mouse is always moved to the left.
https://www.youtube.com/watch?v=v9fidHT52nA

**Comment by Eideren** [comment]
Probably my fault, I'm on it !

**Comment by DaveTheGameDev** [comment]
Nice work @Eideren. She is working perfectly now!
