### ISSUE TITLE
SpriteBatch poor performance in 2D compared to MonoGame

### ISSUE THREAD

**Issue by ryancheung** [xenko3d/xenko#428]
SpriteBatch poor performance in 2D compared to MonoGame.

I've got very poor 2d performance on SpriteBatch. Compared to MonoGame, my game only got ~500FPS, but in MonoGame, it can be ~700-800FPS.

And I found another performance issue:

If I do:
`Sprite = new SpriteBatch(Device, 5000, 1000);`

The FPS Drop nearly 40% percent. The default buffer element count is 1024, and batch capaticy is 64 when initializing SpriteBatch.

There should be some poor performance code in SpriteBatch internal array resizing.

**Comment by ryancheung** [comment]
My 2d game have lots of textures to draw(around 8000 triangles and 1000 draw-calls).
And I believe https://github.com/xenko3d/xenko/blob/master/sources/engine/Xenko.Graphics/BatchBase.cs#L408

is where the performance issue lied down.

**Comment by ryancheung** [comment]
![cpu-profiler-xenko](https://user-images.githubusercontent.com/240899/55317935-22febb80-54a4-11e9-9d30-72933551ca25.PNG)

According the cpu profile result: 
`Xenko.Graphics.CommandList.MapSubresource(GraphicsResource, Int32, MapMode, Boolean, Int32, Int32)` is the most time-cost method, which calls 
`SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource, Int32, MapMode, MapFlags, out DataBox)`

**Comment by ryancheung** [comment]
![cpu-profiler-xenko-2](https://user-images.githubusercontent.com/240899/55318623-c6040500-54a5-11e9-95db-fb27996c4a9d.PNG)

**Comment by Kryptos-FR** [comment]
> Compared to MonoGame, my game only got ~500FPS, but in MonoGame, it can be ~700-800FPS.

That's not relevant. Anything higher than 120 FPS cannot be called "poor performance". There is no point of rendering the scene at a higher rate than the screen refresh rate. If you want a fair comparison, try a game where the framerate is close to that refresh rate.

Xenko and monogame makes different architecture and performance tradeoff decisions. Sure, the commandlist has some overhead but the point is to actually have better performance when it maters (i.e. when the FPS would normally drop much lower). I can write a fixed-pipeline that only clears the screen and has 1000+ FPS, but it doesn't make that "engine" any better.

To be clear, I'm not saying there is nothing wrong or that could be improved in Xenko just that your test case and comparison is not a good one.

**Comment by Eideren** [comment]
@ryancheung included more context on discord, here's an excerpt that seems more relevant:
"[I tested a FPS drop heavely case. In game, I cast a lot of firewall(4x4 cell) effects in ground, which means generating a lot of animated sprites, and FPS drops speedly from ~450 to ~20 [...] In MonoGame, FPS can drop from 800 to ~100](https://discordapp.com/channels/500285081265635328/500285081265635330/562252512887963659)"[sic]

It would be nice if you could create a repro' or include more info regarding the 20 fps case.

**Comment by ryancheung** [comment]
In local single player test, FPS can drops from 520 to 40. Until it goes below 30~, the FPS are acceptable.

I'll update the report if the game FPS drops to ~20 in a heavy-load case. Let's just keep this open for now.

And after some time in future. I'll test the game in Mobile and see the performance.

**Comment by ryancheung** [comment]
Just had another performance test and it shows how FPS drops in Xenko to below 30:

1. Blank case and FPS ~300  in Xenko.
![xenko-2](https://user-images.githubusercontent.com/240899/55695998-a01eb900-59ed-11e9-98c4-f3301e910606.PNG)

2. FPS drops to 27 in Xeko.
![Xenko](https://user-images.githubusercontent.com/240899/55696038-d2301b00-59ed-11e9-95af-5b32346be3c6.PNG)

3. FPS drops to 52 in MonoGame
![MonoGame](https://user-images.githubusercontent.com/240899/55696047-dceab000-59ed-11e9-9346-fa6be4c0edc2.PNG)

**Comment by ryancheung** [comment]
@xen2 Thanks for the memory leak fix and I’ll test it if the fix also improving performance. Thank you for your work!

**Comment by xen2** [comment]
@ryancheung thanks, keep me posted!

**Comment by ryancheung** [comment]
@xen2 The memory leak bug is actually fixed. But it seems not improving the performance.

**Comment by Kryptos-FR** [comment]
Depends on how you use sprites and how many of them. Without a repro project, posting image rendering is not going to help solve the issue.
