### ISSUE TITLE
Game.GraphicsDeviceManager.IsFullScreen set to true then set false cause game window disappeared.

### ISSUE THREAD

**Issue by ryancheung** [xenko3d/xenko#433]
**Release Type**: Official Release/GitHub (please choose appropriate option)
3.1.0.1 beta02
**Version**: Version number and/or git branch

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows
**Describe the bug**
`Game.GraphicsDeviceManager.IsFullScreen` set to true then set false cause game window disappeared.

Sample code:
```
DXManager.Game.GraphicsDeviceManager.IsFullScreen = !DXManager.Game.GraphicsDeviceManager.IsFullScreen;
DXManager.Game.GraphicsDeviceManager.ApplyChanges();
```

And I forgot to put that After game window disappeared, the size of Game.GraphicsDevice.Presenter.BackBuffer is changed weirdly, it's not equal to the size before toggle fullscreen.

**Comment by phr00t** [comment]
I tested this method of setting fullscreen on & off to work much better:

https://github.com/phr00t/xenko/commit/58fddf1b3853af5202feba7ee0016f24cfd9985d
