### ISSUE TITLE
Migrating a project from 3.0 to 3.1 breaks the ability to mark assets as root assets.

### ISSUE THREAD

**Issue by profan** [xenko3d/xenko#442]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta02-0550

**Platform(s)**: All

**Describe the bug**
Create a project in 3.0, migrate it to 3.1, try to include any asset as a root asset when under the new 3.1 project structure and find it doesn't get included (like a Scene/GraphicsCompositor).

**To Reproduce**
1. Create a new 3.0 project.
2. Open it in 3.1.0.1-beta02-0550, upgrading it.
3. Create a new Scene or GraphicsCompositor/any asset not included in some property in the editor/serialized that way (and mark it as a root asset).
4. Try to use Content.Load<WhateverAssetType>("UrlToAssetHere") and find that the ContentManager does not find the asset, and indeed if you look at the project structure in the actual files, it is not marked as a root asset.

**Expected behavior**
I expect the upgrade from 3.0 to 3.1 to not break marking things as a root asset.

**Additional context**
If necessary, I can provide a  small repro project..
Also note that this asset has been reported before, but the user closed the issue as they worked around it, but it is still a problem (and I've also personally encountered it now at least twice): https://github.com/xenko3d/xenko/issues/312

**Comment by guygodin** [comment]
Having the same issue here on a project upgraded from 3.0.0.6 to 3.1
