### ISSUE TITLE
Bug report: VS 2019 Android build error

### ISSUE THREAD

**Issue by slango0513** [xenko3d/xenko#461]
**Release Type**:
Official Nuget

**Version**: 
3.1 beta 2

**Platform(s)**:
Android

**Describe the bug**
Unable to build Android using Visual Studio 2019, need to manually delete the armeabi line in Nuget *.ssdeps. E.g:
C:\Users\<user_name>\.nuget\packages\xenko.core\3.1.0.1-beta02-0550\runtimes\any\lib\monoandroid81\Xenko.Core.ssdeps
After removing "NativeLib;armeabi\libcore.so;armeabi\libcore.so", project can be successfully built.
May be related to:
https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.2#removal-of-support-for-armeabi-cpu-architecture

**To Reproduce**
1. Using VS 2019 16.1 Create new Xamarin Android project, add Xenko.Engine nuget.
2. Abis select only armeabi-v7a.
3. MainActivity : AndroidXenkoActivity { override void OnCreate { base.OnCreate(savedInstanceState); Game = new MainGame(); Game.Run(); } }
4. Build.

**Expected behavior**
Build aborted.

**Comment by slango0513** [comment]
<img width="870" alt="批注 2019-06-04 062612" src="https://user-images.githubusercontent.com/39337503/58838614-ca10f680-8691-11e9-862f-8c87b82c7944.png">

**Comment by xen2** [comment]
@slango0513 No new release has been done yet. Will do one today.
