### ISSUE TITLE
Adding asset failing

### ISSUE THREAD

**Issue by oschakravarthi** [xenko3d/xenko#465]
In the latest release, when I try to add any asset (except .fbx) it is not importing the asset. It is not even displaying any error.

It was working fine in previous release.

**Comment by xen2** [comment]
Sorry, might be related to #458.
I'll revert it and do a new release as soon as I am back home.

**Comment by xen2** [comment]
@oschakravarthi out of curiosity, what is your OS? (which version of Windows)

**Comment by xen2** [comment]
@oschakravarthi Also, could you:
- Download Dependency Walker x64 from http://www.dependencywalker.com/
- Open file `%USERPROFILE%\.nuget\packages\xenko.assets.models\3.1.0.1-beta02-0614\lib\net472\x64\assimp-vc140-mt.dll`
- Post a screenshot. Should look like this:
![image](https://user-images.githubusercontent.com/527565/58986478-be324b00-87dd-11e9-90f9-9bd6d6c82d73.png)

**Comment by tebjan** [comment]
just tested this: when building Xenko.sln locally it works fine. but it fails silently when using the beta 614 from the launcher.
so i guess it can only be a minor thing that some dll is not found at runtime in the launcher version.

**Comment by xen2** [comment]
@tebjan It worked on my computer.
Testing on a clean Windows 10 VM now.

**Comment by xen2** [comment]
Note: beta615 fixed the issue (revert).
I will try it on a clean machine before reactivating the new code.
