### ISSUE TITLE
Can't create Archive for Android

### ISSUE THREAD

**Issue by donnyv** [xenko3d/xenko#469]
After installing version 3.1.0.1 beta02-0615 when I go to create an archive it gives me this message. "AndroidManifest.xml //uses-sdk/@android:minSdkVersion '10' is less than API-16, this configuration is not supported."

This the first android project I'v created. I installed VS2019 with Xamarin.  I have Android SDK Platform 27 installed. I also have Android SDK Tools 26.1.1 installed and Android SDK Build Tools 28.0.3 & 25.0.3 installed

**Comment by donnyv** [comment]
I fixed this by changing my AndroidManifest.xml minSdkVersion to 16

**Comment by xen2** [comment]
Reopening: we need to fix our project templates to use minSdkVersion 16 as well.
