### ISSUE TITLE
XA4301: Cannot determine abi of native library

### ISSUE THREAD

**Issue by donnyv** [xenko3d/xenko#470]
Build fails with
![image](https://user-images.githubusercontent.com/2224189/59323281-179bed80-8ca8-11e9-9d23-886a8627b225.png)

VS2019

**Comment by Kryptos-FR** [comment]
Do you have all the prerequisites to build for Android? You are providing too little information.

Also please follow the correct issue template. It doesn't look like a question, but more like a bug report which template is different.

Thanks.

**Comment by donnyv** [comment]
Sorry for that. Wasn't sure if this was just me doing something wrong or a bug. 

 I installed VS2019 with Xamarin. I have Android SDK Platform 27 installed. I also have Android SDK Tools 26.1.1 installed and Android SDK Build Tools 28.0.3 & 25.0.3 installed

**Comment by xen2** [comment]
Forgot to delete a few `armeabi` files when fixing #461.
Will fix that right away so that it is included in next release.
