### ISSUE TITLE
Doku and Examples for Coders 

### ISSUE THREAD

**Issue by CharlesWoodhill** [xenko3d/xenko#476]
**Is your feature request related to a problem? Please describe.**
sourceCode is vastly and no overview/documentation is out there,  every time i try to learn xenko source i give up again fast. the old method of learning by debugging dont really work here (time efficient) in my opinion 
there is some doku availible but mostly only GameStudio driven 

**Describe the solution you'd like**
i would like some sort of architecture sheet. at least all the (120+?) projects should be described with: a summary, used for, used where, os-support, editor or codeonly, ...
in a 2nd step something like that should be done for classes

i heared its mostly the same api like xna (i never done) so maybe some description of 
the concepts will help too, or at least some links to xna-info may help.

**Describe alternatives you've considered**
none

**Additional context**
examples:
creation of a code only "hello world" app failed, because missing info: 
os window creation/binding
scene setup, setup a scene was easy, but 
 how get a default "graphicComposition" ?
 how connect it to camera of the scene ?
 how conect the camera to a viewport ? 
 where is the viewport ?

the problem is u only get a black/gray window, and u simply dont know whats where missing.

**Comment by Kryptos-FR** [comment]
There is a code-only example: https://github.com/xen2/Xenko.CodeOnlySample
There is documentation for the engine: https://doc.xenko.com/latest/en/

**Comment by CharlesWoodhill** [comment]
i know the example and the doku u mentioned but, its the gameStudio driven doku which dont span programming classes (for example Xenko.Core.Presentation is missing).
the code only example doesnt include some sorts of viewport in an osWindow nor provide an example of the creation of an Graphics Compositor (i can do it gameStudio, but i dont get it running by code :( ) and how u do a similar thing like scene -> camera -> viewport. since ive trouble there.

**Comment by CharlesWoodhill** [comment]
i also added an example in #80

**Comment by fdrobidoux** [comment]
The engine is still very young. It's come a long way in being a usable engine, but it lacks the popularity XNA/MonoGame, Unity or UnrealEngine has.

I say, if you want more "doku" (What's that about, anyway? Call it either doc or documentation) then make your own blog posts and tutorials about Xenko. Or alternatively, put up bounties on subjects you'd like to be explained further, so people have an incentive to do the legwork.

Either way, it won't happen from inaction.

**Comment by fdrobidoux** [comment]
I just had an epiphany : The runtime librairies are not compiled with xml documentation, yet includes a boatload of xml doc comments in its source files, and the `XML documentation file:` option in all projects settings (**Build** tab -> **Configuration:** `Release` -> **Output** region) are not checked for the Release configuration.

I could go through all projects configs and enable that option for Release builds, then I'll make a pull request for it. Shouldn't take too long.

@xen2 : Tell me if that sounds good, and if we should create a new issue for it, or use this one ? Thanks !

**Comment by fdrobidoux** [comment]
Commit https://github.com/xenko3d/xenko/commit/a4c7c1a748c8a576d5464559c5460b73b3f6ca87 has tried to generate the xml doc files, but they don't seem to be bound correctly when replacing in the references the downloaded packages with the built ones in a new Xenko project.

Something else needs to be done so that the nuget packages can inform that the xml doc is present.
