### ISSUE TITLE
Shader syntax highlighting in visual studio seems to be broken

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#491]
**Release Type**:
Official

**Version**: Version number and/or git branch
3.1.0.1-beta02-0635

**Platform(s)**: Does the problem occur on Windows, Android...?
any

**Describe the bug**
visual studio doesn't highlight shader syntax anymore

**To Reproduce**
1. create a new shader file
2. no syntax highlighting in visual studio text editor

**Expected behavior**
shader code should have syntax highlighting

**Comment by devjarmo** [comment]
Wow, didn't even know there was syntax highlighting for this!

**Comment by tebjan** [comment]
latest VS plugin seems to fix this.
