### ISSUE TITLE
Not able to import any assets.

### ISSUE THREAD

**Issue by oschakravarthi** [xenko3d/xenko#495]
Not able to import any 3d models except FBX. Game studio is not even showing any errors/warnings. Just keeps quite. I am using the latest version: 3.1.0.1-beta02-0635

Very unstable product.

**Comment by Bloodshoot111** [comment]
Well I'm not an developer but comments like very unstable product are not for GitHub issues. Keep that for yourself or go to the Forums/Discord.

**Comment by xen2** [comment]
@oschakravarthi Does installing latest Visual C++ x64 redist helps?
Here is the link: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by xen2** [comment]
Duplicate of #465. Will be part of next release.

**Comment by xen2** [comment]
Should be fixed in latest beta (674)
