### ISSUE TITLE
Shader's parameter doesn't work at Runtime.

### ISSUE THREAD

**Issue by TracyLestrade** [xenko3d/xenko#498]
I wrote a shader like this. when I use with Template arguments[&lt;float Percentage&gt;], It works fine. but I use with Parameter[stage float Percentage]. I can change this value. but it didn't have any change on rendering.
btw. I wonder what's the difference between Effect and Shader.
thanks.
```
//Countdown.xksl
shader Countdown : ComputeColor, Texturing
{
    //compose float Percentage = 0.0f;
    stage float Percentage = 0.0f;

    float3 hsv2rgb(float h, float s, float v)
    {
        float pi = 3.14159;
        float3 result = float3(1,1,1);
        float p6 = pi / 3;
        float i  = floor(h / p6);
        float f = fmod(h, p6);

        float p,q,t;
        p = v * (1 - s);
        q = v * (1 - f * s);
        t = v * (1 - (1 - f) * s);
        if(i<1)
            result = float3(v,t,p);
        else if(i<2)
            result = float3(q,v,p);
        else if(i<3)
            result = float3(p,v,t);
        else if(i<4)
            result = float3(p,q,v);
        else if(i<5)
            result = float3(t,p,v);
        else if(i<6)
            result = float3(v,p,q);

        return result;
    }

    override float4 Compute()
    {
        float pi = 3.14159;
        float2 uv = streams.TexCoord.xy;
        float2 dir = uv - float2(0.5,0.5);
        float len  = length(dir);
        dir = normalize(dir);
        float radius = 0;

        float2 uy = float2(0,-1);
        float2 ux = float2(1,0);
        float dy = dot(uy,dir);
        float dx = dot(ux,dir);

        if(dy>0)
        {
            if(dx>0)
                radius = acos(dy);
            else
                radius = 2 * pi - acos(dy);
        }
        else
        {
            if(dx>0)
                radius = pi - acos(-dy);
            else
                radius = pi + acos(-dy);
        }

        float4 c = float4(1,1,1,1);
        if(radius < Percentage * 2 * pi)
            c = float4(hsv2rgb(radius,1,1),1);
        return c;
    }
};
```
```
//Countdown.cs
namespace CustomEffect
{
    public static partial class CountdownKeys
    {
        public static readonly ValueParameterKey<float> Percentage = ParameterKeys.NewValue<float>(0.0f);
    }
}
```
```
//TestScript.cs
public override void Update()
{
    double ts = Game.PlayTime.TotalTime.TotalSeconds;
    ts = (ts % 3) / 3;

    Entity.Get<ModelComponent>().Materials[0].Passes[0].Parameters.Set(CountdownKeys.Percentage, (float)ts);
    // Do stuff every new frame
}
```

**Comment by tebjan** [comment]
> Entity.Get<ModelComponent>().Materials[0].Passes[0].Parameters.Set(CountdownKeys.Percentage, (float)ts);

i think Pass[0] doesn't contain your custom shader parameter... you rather have to find the shader instance and set the parameter there. like
on start:
`var myShader = SomehowGetShaderInstance();`
on update:
`myShader.Parameters.Set(CountdownKeys.Percentage, (float)ts);`

**Comment by TracyLestrade** [comment]
I have no idea about shader instance. how can I retrieve shader instance. by LoadEffect method?

At 2019-08-15 22:31:48, "Tebjan Halm" <notifications@github.com> wrote:


Entity.Get().Materials[0].Passes[0].Parameters.Set(CountdownKeys.Percentage, (float)ts);

i think Pass[0] doesn't contain your custom shader parameter... you rather have to find the shader instance and set the parameter there. like
on start:
var myShader = SomehowGetShaderInstance();
on update:
myShader.Parameters.Set(CountdownKeys.Percentage, (float)ts);

**Comment by xen2** [comment]
@TracyLestrade 
Please put the variable in the material cbuffer:
```
cbuffer PerMaterial
{
    stage float Percentage = 0.0f;
}
```

Then I think your original approach (`Materials[0].Passes[0].Parameters.Set(...)`) should work better.

**Comment by TracyLestrade** [comment]
yes. That's the question! Thanks. @xen2 
I would like to ask one. 
what's the difference between with cbuffer and without cbuffer qualifier.

**Comment by tebjan** [comment]
> what's the difference between with cbuffer and without cbuffer qualifier.

yes, cbuffer is the constant buffer:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-constants

there can be more than one constant buffer, if you don't specify the name of the constant buffer, the value gets added to the default constant buffer, which xenko might handle differently than the PerMaterial one.

**Comment by devjarmo** [comment]
@TracyLestrade @tebjan This needs updated in the documentation? I must be following in Tracy's footsteps, I believe I've hit the same issue and it's not on this page:

https://doc.xenko.com/latest/jp/manual/graphics/effects-and-shaders/custom-shaders.html

Perhaps some clarification is needed to the text box with the Parameters.Set code example.

**Comment by TracyLestrade** [comment]
Yes. I checked document. and referred to  the xenko sample “CustomEffect”. they don't use the cbuffer neither. I still don't understand why CustomEffect works fine.

**Comment by devjarmo** [comment]
The game project probably references some older libraries. Definitely works with cbuffer though. 👍🏼

**Comment by xen2** [comment]
@TracyLestrade `CustomEffect` instantiates the effect itself and works with `EffectInstance.Parameters` which is the global cbuffer.

Of course, some could be done to change cbuffer mesh rendering but it's not trivial: you need to loop over all effect instances, so you need to hookup inside `RenderFeature`.
`PerMaterial` cbuffer offer a much better entry point for changing rendering parameters live easily from a script.

All that said, `PerMaterial` parameters is definitely worth a tutorial/sample in the doc so that people don't struggle to find how to do this.

**Comment by xen2** [comment]
Note: it would probably make lot of sense in https://github.com/xenko3d/xenko/tree/master/samples/Graphics/MaterialShader
