### ISSUE TITLE
Editor: Theme

### ISSUE THREAD

**Issue by RUSshy** [xenko3d/xenko#50]
Hi

The editor could get a little lift

There is just too many information, and too many colors, contrast is weird

Should go with a real dark / light theme, not something in the middle

Unity is about to get a new theme, the current one is already readable, but the new one is even better, it put the focus on the scene view, nothing busy, nothing fancy

![ca2fb1b4-6250-498f-a873-9673f8eec2d6](https://user-images.githubusercontent.com/18348637/43683770-0a9a933e-9893-11e8-9923-ece4db51cfed.png)

![17ca1803-e648-4a9f-acce-157fdaa34d55](https://user-images.githubusercontent.com/18348637/43683771-0c21c312-9893-11e8-887d-947537d36215.png)

**Comment by RUSshy** [comment]
I think i'll be able to contribute on this one

**Comment by Kryptos-FR** [comment]
That's a good idea. We never took the time to properly cleanup the theme.

Most of the colors/styles/templates are defined in https://github.com/xenko3d/xenko/blob/master/sources/presentation/Xenko.Core.Presentation/Themes/ExpressionDark/Theme.xaml. There might be some other location where the colors are hardcoded, so that would be a good time to cleanup that and make sure everything is in the same theme.

Once that is done, the next step would be to provide a white/gray theme. Some people don't like dark themes (for example Michael from GameFromScratch). A high-contrast theme could also be a good idea.

**Comment by Kryptos-FR** [comment]
Work can be done in parallel with #4 but might need some synchronization to make sure the images/icons fit with the new theme.

**Comment by qril** [comment]
I don't think that xenko has a future with this clunky WPF thing. You should ditch it ASAP.
Why didn't you do something like unity did? Immediate gui proven to be quite a success.

**Comment by Hansolo128** [comment]
@qril that's just opinion. I like xenko's editor far more than unity's visually, even with it being rough around the edges. it's one of the reasons I wanted to try sticking with the engine. That and native .net implementation.

**Comment by Kryptos-FR** [comment]
@qril if you work on a new UI that can support all the cases and scenario of the current editor, I'd be glad to review your merge request ;)

**Comment by 0xaryan** [comment]
@qril @RUSshy WPF is an awesome graphical system. There is nothing wrong with it (as you might know, Visual Studio and Visual Studio Blend are also written in WPF).
So, why not some inspirations from Dark Blend?

### Project Selection
![Project Selection](https://github.com/0xaryan/MediaMan/raw/master/Github/Issues/Xenko/EditorTheme/ProjectTemplate.png)


### Consistent UI
![Project Selection](https://github.com/0xaryan/MediaMan/raw/master/Github/Issues/Xenko/EditorTheme/Loading.PNG)

### Dark Xenko
![Project Selection](https://github.com/0xaryan/MediaMan/raw/master/Github/Issues/Xenko/EditorTheme/XenkoDark.png)

**Comment by tzachshabtay** [comment]
> WPF is an awesome graphical system. There is nothing wrong with it

There is one thing wrong with it: it's not cross platform.

**Comment by RUSshy** [comment]
I agree WPF is awesome and quite easy to customize, i'm only afraid about custom editor plugins, in unity it is really simple to create custom UI

@0xaryan 

is your current progress available somewhere ? i'm also trying to clean the theme, maybe we should join force

**Comment by qril** [comment]
It's not cross-platform. It's hard to maintain and extend. You need to host your game in another environment which make things more complicated. WPF (and all xaml based products in general) is complicated and over-engineered beast.
As far as I know all popular engine's editors (unity, godot, ue4) are implemented just as a game running by the engine itself. There is a rationale behind this. This will open a lot of new possibilities.

What we need is an editor as unified platform for content authoring tools and runtime components as assets/packages developed by community. Xenko developers should really focus on providing such platform first, not on implementing specific tools on top of old WPF editor.

**Comment by Kryptos-FR** [comment]
@qril I don't think you realize how big a task it is to implement such UI. We are talking about months (years?) of development with no guarantee to reach the same level of functionalities that are currently available in the editor.

Until our community grows is a much higher number, I don't think it is worth to spend time on that.

> It's not cross-platform.

So what? The market/target audience for games is mostly on Windows and mobiles. Xenko already supports building for Linux, Xamarin and MacOS could be supported. Even then, you would not make a game only for Linux or MacOS anyway but you would also target Windows. Therefore having the editing/build tools on Windows only is not such a big deal.

> It's hard to maintain and extend.

Not necessarily. WPF has some limitations but it is not that hard to maintain, especially with its templating/style capabilities. But if you are talking on extending the editor itself, then WPF is not a limiting factor. We can make it work to allow plugins. In fact, although incomplete, its architecture is already plugin-based in some areas. And we could also look at pattern/libraries such as Prism.

> Xenko developers should really focus on providing such platform first, not on implementing specific tools on top of old WPF editor.

1. There is no such thing as "Xenko developers". We are a community now 😉. The only full-time developer at the moment is @xen2 and I would rather see him work on the engine and let the editor be improved by the community.
2. As I said earlier, it is a huge task. I don't think we should allocate the whole community to making yet another editor. So opposite to you I think we should first focus on improving the existing user experience and add more tools and functionalities.

I'm not saying that if someone or a group of people wants to start to work on a new editor, they shouldn't. By all means, if you are motivated, go for it. But I don't think that it should be the main focus of the community.

All that said, you have the right to disagree with me.

**Comment by 0xaryan** [comment]
> is your current progress available somewhere ? i'm also trying to clean the theme, maybe we should join force

@RUSshy Yes. I already made some changes in colors, menus, icons and some other items. They are now available in my fork of Xenko.

**Comment by Toriadus** [comment]
Here are my remarks
![ui](https://user-images.githubusercontent.com/42056644/44051031-69c41358-9f41-11e8-8ac3-3cd8c180d7b6.png)

**Comment by Toriadus** [comment]
Variant Dark Xenko isn't the most successful from the point of visual perception , too sharp contrast of black color and light colors. My opinion - the ideal option would be a gray color with a light gradient of monochrome icons like Blender 3D, Modo, Atomic Game Engine, Wave Game Engine, Shiva Game Engine etc. This is the most favorable option for the eyes.

![blender264_interface](https://user-images.githubusercontent.com/42056644/44056589-5f480618-9f51-11e8-9b6c-4fbf13fbfb0a.jpg)
![robobeach2017](https://user-images.githubusercontent.com/42056644/44056612-6989311a-9f51-11e8-8ae3-98640998f163.png)
![sffbzqr](https://user-images.githubusercontent.com/42056644/44056618-6e6803c8-9f51-11e8-971d-d15b468f73a4.png)
![mosque3](https://user-images.githubusercontent.com/42056644/44056626-731cbb8e-9f51-11e8-964a-7ee9e3d187d8.jpg)
![makinggameassetsw_modo_scrnsht02](https://user-images.githubusercontent.com/42056644/44056758-d68b9f1e-9f51-11e8-836d-597378826dd6.jpg)

**Comment by Kryptos-FR** [comment]
@toriadus you should have a look at #83 as we are about to merge it. Any feedback welcome!

**Comment by Toriadus** [comment]
Tnx

**Comment by xen2** [comment]
@RUSshy @0xaryan OK to close this issue with #89 merge, or is there some additional work to do?
