### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by oschakravarthi** [xenko3d/xenko#500]
When I create a new Game and when I press the Run icon in the game studio, it builds the game but it is not launching the game.

When I open the solution in the VisualStudio and run, I am getting the below exception. 
Please fix it asap because, there is no point if we cannot run the game.
I am using the most recent version of Xenko (3.1.0.1-Beta02-0674) 

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '<Module>' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
TypeInitializationException: The type initializer for '<Module>' threw an exception.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'Xenko.Graphics, Version=3.1.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by ideonella** [comment]
I got this as well. Resolved by using the NuGet console to install https://www.nuget.org/packages/Xenko.Graphics/

I got a probably unrelated network error after, but until that is resolved I can't say for certain whether or not simply installing the package will fix the issue.

**Comment by xen2** [comment]
Should be fixed by tomorrow

**Comment by Eideren** [comment]
This should already be fixed on latest master-3.1 afaik ?

**Comment by xen2** [comment]
@Eideren yes, thanks!
