### ISSUE TITLE
[ContributionRequest] Getting the UIElement under the mouseCursor

### ISSUE THREAD

**Issue by CharlesWoodhill** [xenko3d/xenko#508]
I havent found a method to get the control under the mouse,
since that feature exists private in UIRenderFeature it only needs to be exposed,

This could be used to consume a click when handling mouse input.

in file UIRenderFeature.Picking.cs:
make the variable mouseOverElement (in private UpdateMouseOver() ) a public property.

is that ok? if so i would start work :)

**Comment by fdrobidoux** [comment]
Make a draft pull request and go at it in your own fork m8!

**Comment by CharlesWoodhill** [comment]
done
