### ISSUE TITLE
CompilerApp error on build

### ISSUE THREAD

**Issue by SilentCLD** [xenko3d/xenko#519]
**Release Type**: GitHub master

**Version**: 3f3158783ec94c9f4705e3afd50e671b05b2ed15

**Platform(s)**: Windows

**Describe the bug**
CompilerApp is failing to build causing game projects to not compile through Game Studio

**To Reproduce**
1. (Re)build source

**Expected behavior**
Building shouldn't produce any errors.

**Log and callstacks**
[xenko_callstack.txt](https://github.com/xenko3d/xenko/files/3654559/xenko_callstack.txt)

**Comment by profan** [comment]
Running into this same error on 3.1.0.1 as well.

**Comment by fdrobidoux** [comment]
I can confirm, I'm getting the exact same error.

**Comment by Eideren** [comment]
Does this error still occur for you ? I can't reproduce it on branch master-3.1

**Comment by xen2** [comment]
Should be fixed in latest master-3.1 with https://github.com/xenko3d/xenko/commit/297d239cc89ddee88d4cc52448336b35fa93080d

**Comment by SilentCLD** [comment]
Yep can confirm successful building with master-3.1
