### ISSUE TITLE
Open VR / Steam VR support

### ISSUE THREAD

**Issue by HeadClot** [xenko3d/xenko#53]
Hey would it be possible to get OpenVR support for Xenko?

I am going through the API docs and seeing that there is no direct support for OpenVR.

https://github.com/ValveSoftware/openvr

**Comment by tebjan** [comment]
What exactly do you mean by "OpenVR support"? Xenko is using OpenVR as one of their VR backends:
https://github.com/xenko3d/xenko/tree/master/sources/engine/Xenko.VirtualReality

**Comment by HeadClot** [comment]
Oh my bad. I was looking through the API docs and saw that there was no mention of OpenVR.

https://doc.xenko.com/3.0/en/api/Xenko.VirtualReality.html
