### ISSUE TITLE
Can't build games because of missing assemblies

### ISSUE THREAD

**Issue by hammeron-art** [xenko3d/xenko#539]
**Release Type**: GitHub

**Version**: 9603bbd0ce022f1df179251c7e6986f9a7ed0303

**Platform(s)**: Windows 10

**Describe the bug**
I built Xenko from source in Visual Studio 2019 and the Game Studio is working. However, I can't run any project. There is no error in the output of the Game Studio when I press build but the game never starts. When I build in Visual Studio it throws a FileNotFoundException about Xenko.Graphics assembly.

Xenko.Graphics builds fine and there are many other Xenko assemblies in the game project's Bin directory but Xenko.Graphics isn't there. If I copy Xenko.Graphics.dll manually then another FileNotFoundException Xenko.VirtualReality so I guess many assemblies are missing.

**To Reproduce**
1. I try building any of the sample project.
2. Don't run with the Game Editor. FileNotFoundException with Visual Studio.

**Expected behavior**
Start the game.

**Log and callstacks**
SpaceEscape in Xenko Game Studio:
> [(0,0)]: Info:Assembly [SpaceEscape.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
> [(0,0)]: Info:SpaceEscape.Game -> C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Game\bin\Debug\netstandard2.0\SpaceEscape.Game.dll
> [(0,0)]: Info:Patch for assembly [SpaceEscape.Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
> [(0,0)]: Info:SpaceEscape.Windows -> C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\SpaceEscape.Windows.exe
> Info:BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path=C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\data --build-path=C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\obj\xenko\assetbuild\data --package-file=C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\SpaceEscape.Windows.csproj --log-pipe=net.pipe://localhost/Xenko.Core.Assets.Editor.2de0cb3d-498b-4250-a4cd-5032ca102171 --verbose
> Info:Starting builder.
> [C:/Users/CHRISTIAN/Documents/Xenko Projects/SpaceEscape/SpaceEscape.Game/Effects/TransformationTextureUV.xksl(6,5)]: Warning: W0202: The stage keyword is missing in The method declaration [override void VSMain() {...}] in class [TransformationTextureUV]
> [C:/Users/CHRISTIAN/Documents/Xenko Projects/SpaceEscape/SpaceEscape.Game/Effects/TransformationTextureUV.xksl(6,5)]: Warning: W0202: The stage keyword is missing in The method declaration [override void VSMain() {...}] in class [TransformationTextureUV]
> Info:Build finished in 906 steps. Command results: 0 succeeded, 906 up-to-date, 0 failed, 0 not triggered due to previous failure.
> Info:Build is successful.
> Info:Generate bundles: Scan assets and their dependencies...
> Info:Generate bundles: Assign assets to bundles...
> Info:Generate bundles: Compress and save bundles to HDD...
> Info:Generate bundles: Done
> [(0,0)]: Info:Deployment of SpaceEscape.Windows successful.

**Comment by Usman4D** [comment]
Same but i can build with vs

**Comment by xen2** [comment]
There was a fix in `master-3.1` but not in `master`.
This should now be merged and working with latest `master`, please try again.

**Comment by hammeron-art** [comment]
@xen2 I still can't build but now the FileNotFoundException appears in the output. 

> [(0,0)]: Info:Assembly [SpaceEscape.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
> [(0,0)]: Info:SpaceEscape.Game -> C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Game\bin\Debug\netstandard2.0\SpaceEscape.Game.dll
> [(0,0)]: Info:Patch for assembly [SpaceEscape.Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
> [(0,0)]: Info:SpaceEscape.Windows -> C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\SpaceEscape.Windows.exe
> [(0,0)]: Info:
> [(0,0)]: Info:Excecao Sem Tratamento: System.TypeInitializationException: O inicializador de tipo de '<Module>' acionou uma excecao. ---> System.TypeInitializationException: O inicializador de tipo de '<Module>' acionou uma excecao. ---> System.IO.FileNotFoundException: Nao foi possivel carregar arquivo ou assembly 'Xenko.Graphics, Version=3.2.0.1, Culture=neutral, PublicKeyToken=null' ou uma de suas dependencias. O sistema nao pode encontrar o arquivo especificado.
> [(0,0)]: Info:   em Xenko.Core.Serialization.AssemblyScan.Xenko_AssetsAssemblyScan.Initialize()
> [(0,0)]: Info:   em .cctor()
> [(0,0)]: Info:   --- Fim do rastreamento de pilha de excecoes internas ---
> [(0,0)]: Info:   em Xenko.Core.DataSerializers.Xenko_Core_Assets_CompilerAppSerializerFactory.Initialize()
> [(0,0)]: Info:   em .cctor()
> [(0,0)]: Info:   --- Fim do rastreamento de pilha de excecoes internas ---
> [C:\Users\CHRISTIAN\.nuget\packages\xenko.core.assets.compilerapp\3.2.0.1-beta01\buildTransitive\Xenko.Core.Assets.CompilerApp.targets(68,5)]: Error:O comando ""C:\Users\CHRISTIAN\.nuget\packages\xenko.core.assets.compilerapp\3.2.0.1-beta01\buildTransitive\..\lib\net472\Xenko.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\data" --build-path="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\obj\xenko\assetbuild\data" --package-file="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\SpaceEscape.Windows.csproj" --log-pipe="net.pipe://localhost/Xenko.Core.Assets.Editor.2fef06f5-2a75-4982-8887-f3869b0c9d1c" --verbose" foi encerrado com o código -532462766.

And Visual Studio throws the same error but at build time instead of runtime.

> 1>------ Build started: Project: SpaceEscape.Windows, Configuration: Debug Any CPU ------
> 1>Assembly [SpaceEscape.Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
> 1>SpaceEscape.Windows -> C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\SpaceEscape.Windows.exe
> 1>
> 1>Excecao Sem Tratamento: System.TypeInitializationException: O inicializador de tipo de '<Module>' acionou uma excecao. ---> System.TypeInitializationException: O inicializador de tipo de '<Module>' acionou uma excecao. ---> System.IO.FileNotFoundException: Nao foi possivel carregar arquivo ou assembly 'Xenko.Graphics, Version=3.2.0.1, Culture=neutral, PublicKeyToken=null' ou uma de suas dependencias. O sistema nao pode encontrar o arquivo especificado.
> 1>   em Xenko.Core.Serialization.AssemblyScan.Xenko_AssetsAssemblyScan.Initialize()
> 1>   em .cctor()
> 1>   --- Fim do rastreamento de pilha de excecoes internas ---
> 1>   em Xenko.Core.DataSerializers.Xenko_Core_Assets_CompilerAppSerializerFactory.Initialize()
> 1>   em .cctor()
> 1>   --- Fim do rastreamento de pilha de excecoes internas ---
> 1>C:\Users\CHRISTIAN\.nuget\packages\xenko.core.assets.compilerapp\3.2.0.1-beta01\buildTransitive\Xenko.Core.Assets.CompilerApp.targets(68,5): error MSB3073: The command ""C:\Users\CHRISTIAN\.nuget\packages\xenko.core.assets.compilerapp\3.2.0.1-beta01\buildTransitive\..\lib\net472\Xenko.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\Bin\Windows\Debug\data" --build-path="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\obj\xenko\assetbuild\data" --package-file="C:\Users\CHRISTIAN\Documents\Xenko Projects\SpaceEscape\SpaceEscape.Windows\SpaceEscape.Windows.csproj" --log-pipe=""" exited with code -532462766.
> 1>Done building project "SpaceEscape.Windows.csproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by hammeron-art** [comment]
Nevermind. I just had to clean and rebuild everything.
Thank you very much!
