### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by NewNodeGames** [xenko3d/xenko#55]
I sent a report but can't add my email because Windows freeze the application with a crash message. How I can locate the report for paste here?

**Comment by NewNodeGames** [comment]
Ok, this is the report, seems a audio related problem:
Application: GameStudio
UserEmail: XorD.fr@gmail.com
UserMessage: 
XenkoVersion: 3.0.0.1
GameStudioVersion: 4
ThreadName: PreviewGame Thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: 
LastActions: 
CurrentDirectory: C:\Program Files\Xenko
CommandArgs: /LauncherWindowHandle 2362344 C:\Users\usuario\Documents\Xenko Projects\MyGame\MyGame.sln
OsVersion: Microsoft Windows 7 Professional  6.1.7601 x64
ProcessorCount: 4
Exception: TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Xenko.Audio.AudioEngine'.
   at Xenko.Audio.AudioEngine..ctor(AudioDevice device, UInt32 sampleRate)
   at Xenko.Audio.AudioSystem.Initialize()
   at Xenko.Games.GameSystemCollection.GameSystems_ItemAdded(Object sender, TrackingCollectionChangedEventArgs e)
   at Xenko.Engine.Game.Initialize()
   at Xenko.Editor.Engine.EmbeddedGame.Initialize()
   at Xenko.Editor.Preview.PreviewGame.Initialize()
   at Xenko.Games.GameBase.InitializeBeforeRun()
   at Xenko.Games.GamePlatform.OnInitCallback()
   at Xenko.Games.GameWindowWinforms.Run()
   at Xenko.Games.GameBase.Run(GameContext gameContext)
   at Xenko.Editor.Preview.GameStudioPreviewService.XenkoUIThread()
   at Xenko.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException:
  Exception: Failed to initialize the audio native layer.
     at Xenko.Audio.AudioEngine..cctor()

GPU0.AdapterCompatibility: Intel Corporation
GPU0.AdapterDACType: Internal
GPU0.AdapterRAM: 1819832320
GPU0.Availability: 3
GPU0.Caption: Intel(R) HD Graphics
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1280
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 800
GPU0.Description: Intel(R) HD Graphics
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20130130000000.000000-000
GPU0.DriverVersion: 8.15.10.2993
GPU0.InfFilename: oem4.inf
GPU0.InfSection: iILKD0
GPU0.InstalledDisplayDrivers: igdumd64.dll,igd10umd64.dll,igdumdx32,igd10umd32
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 59
GPU0.Monochrome: False
GPU0.Name: Intel(R) HD Graphics
GPU0.PNPDeviceID: PCI\VEN_8086&DEV_0042&SUBSYS_83831043&REV_12\3&11583659&0&10
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: USUARIO-PC
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1280 x 800 x 4294967296 colores
GPU0.VideoProcessor: Intel(R) HD Graphics (Core i3)
Log: 1: [PreviewGame]: Error: Unexpected exception. System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Xenko.Audio.AudioEngine'. ---> System.Exception: Failed to initialize the audio native layer.
   en Xenko.Audio.AudioEngine..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Xenko.Audio.AudioEngine..ctor(AudioDevice device, UInt32 sampleRate)
   en Xenko.Audio.AudioSystem.Initialize()
   en Xenko.Games.GameSystemCollection.GameSystems_ItemAdded(Object sender, TrackingCollectionChangedEventArgs e)
   en Xenko.Engine.Game.Initialize()
   en Xenko.Editor.Engine.EmbeddedGame.Initialize()
   en Xenko.Editor.Preview.PreviewGame.Initialize()
   en Xenko.Games.GameBase.InitializeBeforeRun()
2: [SafeAction]: Fatal: Unexpected exception. System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Xenko.Audio.AudioEngine'. ---> System.Exception: Failed to initialize the audio native layer.
   en Xenko.Audio.AudioEngine..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Xenko.Audio.AudioEngine..ctor(AudioDevice device, UInt32 sampleRate)
   en Xenko.Audio.AudioSystem.Initialize()
   en Xenko.Games.GameSystemCollection.GameSystems_ItemAdded(Object sender, TrackingCollectionChangedEventArgs e)
   en Xenko.Engine.Game.Initialize()
   en Xenko.Editor.Engine.EmbeddedGame.Initialize()
   en Xenko.Editor.Preview.PreviewGame.Initialize()
   en Xenko.Games.GameBase.InitializeBeforeRun()
   en Xenko.Games.GamePlatform.OnInitCallback()
   en Xenko.Games.GameWindowWinforms.Run()
   en Xenko.Games.GameBase.Run(GameContext gameContext)
   en Xenko.Editor.Preview.GameStudioPreviewService.XenkoUIThread()
   en Xenko.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()

**Comment by Kryptos-FR** [comment]
Thanks.

We will need to investigate why the audio layer failed, but whatever the reason we should detect and catch that exception when run in the editor game: we don't really care about the audio when editing the game. Worst case the audio preview doesn't work but that shouldn't be a crash condition.

As a side-not and for some background on why the editor crashes often: we decided early that in order to catch as many issues as possible we would crash in almost every case when an exception is thrown (except when explicitly caught for documented reason). That helped us a lot in between some major versions to detect severe issues in our code base. Another reason, is that some exceptions could let the project/assets in undefined states which if saved later could corrupt them.

Now that the project is open-sourced and community-based, we can maybe review that policy and figure out in a more fine grained way which areas are more critical than others and try to recover gracefully where we don't think it would impact integrity. But it is not always easy to determine so.

**Comment by NewNodeGames** [comment]
One question: I need install MSBuild/Visual Studio with C++ pack? Can be the problem? In the source info the requisites are well explained but in the official site is a bit ambigous:

IDE for writing code | Visual Studio 2015 or 2017

**Comment by Kryptos-FR** [comment]
For running the editor or in general for using the released version of Xenko you don't need VS with C++. It is only needed to build from the sources as there are a few projects written in C++ (some partially).

**Comment by NewNodeGames** [comment]
Ok. I have a few questions now: I can disable the audio system for give a try to the engine? Changing something in the archive GameSettings.xkgamesettings for example or other way. Second question, I need to install .Net 4.6.2 sdk and targeting pack? https://doc.xenko.com/latest/en/manual/troubleshooting/xenko-doesnt-run.html
I only have installed 4.6.2 framework.
And finally, where is located editor installation, I can only locate the launcher folder.

**Comment by NewNodeGames** [comment]
Hey, I solved the problem and now the editor is up and running! I just executed install-prerequisites.exe found in the installation folder.
