### ISSUE TITLE
Tutorial: How to Compile xenko for develop on Linux/Ubuntu 18.04.3?

### ISSUE THREAD

**Issue by firebitsbr** [xenko3d/xenko#567]
What are the successful steps for Tutorial: How to Compile xenko for develop on Linux / Ubuntu 18.04.3?

**Comment by Eideren** [comment]
You can't build parts of xenko's codebase from a unix system yet.
You can build your games from linux and mac as long as you don't use the asset compiler.
You can build your games on windows to be run on mac and linux.
https://github.com/xenko3d/xenko/issues/360
https://github.com/xenko3d/xenko/issues/8
