### ISSUE TITLE
CharacterComponent.Orientation initialized as 0,0,0,0 instead of 0,0,0,1

### ISSUE THREAD

**Issue by SeleDreams** [xenko3d/xenko#574]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release

**Version**: Version number and/or git branch
3.1.1

**Platform(s)**: 
Windows 10 Professional 64-bit

**Describe the bug**
When a CharacterComponent is initialized, its Orientation property starting value is 0,0,0,0.
It for instance prevents from multiplicating its value by Quaternion.RotationY in order to rotate its Y axis as the end value is always 0.
replacing it by 0,0,0,1 allows it to properly rotate.

**To Reproduce**
1. Add a Character component to an Entity.
2. Check its Orientation value and try to multiply it by other quaternions to rotate it.

**Expected behavior**
It should initialize as 0,0,0,1 to allow such operations without requiring too much quaternions knowledge to understand the root of issues.

**Comment by phr00t** [comment]
Fix could be cherry picked from my fork: https://github.com/phr00t/FocusEngine/commit/e8e5550b997282c9ca2d2008a2784bb1a9615c71
