### ISSUE TITLE
Make Scripts as ActivableEntityComponent so we can enable or disable them from the editor.

### ISSUE THREAD

**Issue by ennQ** [xenko3d/xenko#576]
**Is your feature request related to a problem? Please describe.**
When i have multiple scripts or multiple entities with a script, i want to enable some scripts and disable some other, but i cant from the editor.

**Describe the solution you'd like**
A checkbox next to the script component to enable or disable it at runtime. (like cameras have)

**Describe alternatives you've considered**
Do it directly from the code with an editor value.

**Comment by Kryptos-FR** [comment]
You can do it manually by adding a boolean property and checking its value in the update method.

The reason it is not provided by default is because having a check for every single script has a performance cost at runtime.

**Comment by ennQ** [comment]
Alright, i guess you're right, im closing this.
