### ISSUE TITLE
Can Veldrid help to simplify graphics API abstraction code?

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#59]
Veldrid looks like a very promising project and could help with graphics api abstraction:
https://github.com/mellinoe/veldrid

not sure if it supports as much as in here:
https://github.com/xenko3d/xenko/tree/master/sources/engine/Xenko.Graphics

but it might still be of help? and maybe @mellinoe is even able to jump in?

**Comment by mellinoe** [comment]
As you can see, they have built their own graphics abstraction already, which is probably tailored specifically for the engine. Perhaps if Veldrid was around back when they were building their engine they could have used it, but it probably wouldn't make sense for them to scrap all of that and switch over to a different library at this point.

**Comment by mellinoe** [comment]
(Oops, didn't see which repo this was posted in)

Veldrid's abstraction is pretty similar to Xenko's, from what I see. If you were building something from scratch, it would make more sense to build on top of an abstraction like Veldrid's, but given that the code in here is already written and tested, etc. there's probably very little to be gained by rewriting it.

**Comment by xen2** [comment]
Interesting, didn't know this project!
Looks like they have many abstractions similar to D3D12/Vulkan like we did, such as `ResourceSet`.

It probably need a careful check/inspection to see if all the custom internal needs we have are available (if we end up having to customize it a lot to the point it's almost a separate fork, there is no point).

Still, lot of work and so many other things to do, so I don't expect this to be checked/happen anytime soon, but let's keep it in mind.

@mellinoe I am curious, how did you generate the OpenGL binding? I wanted to get rid of OpenTK at some point (huge dll, no big improvements in sight, and we mostly need only bindings).

**Comment by tebjan** [comment]
i see, as it is overlapping quite a lot, it would need a comparison by feature. since xenko bindings run fine and having them in the repo makes it more easy to change/add features. 

however, picking only the OpenGL methods needed as in #68 sounds like a good plan for mobile.

**Comment by xen2** [comment]
@tebjan Agree, it won't replace Xenko Graphics code as it is quite tailored to our need and it evolves quite a lot,
I was mostly interested to look into it for specific parts/improvements (such as #68 as you mentioned).

**Comment by tebjan** [comment]
i'd consider this closed then since veldrid is currently not on option.
