### ISSUE TITLE
Error when I installed and tried to launch project

### ISSUE THREAD

**Issue by LunarCoreGames** [xenko3d/xenko#6]
Sorry I am completely new to this engine (and 3D development in general) but after I installed version 3.0.0.1 I received this error:

An error occurred while installing version 3.0.0.1. Value cannot be null. Parameter name: path1 at System.IO.Path.Combine(String path1, String path2) at Xenko.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Xenko.Core.Packages.NugetStore.<InstallPackage>d79.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()

And then when I launched a project it said it couldn't find Microsoft.Net.Sdk

This is probably something very simple and I'm just lost. (Plus I've worked 63hrs this week so my mind isn't functioning at it's best.)

**Comment by pikachuk** [comment]
try to install visual studio 2017 with c# support to get the .net sdk

**Comment by LunarCoreGames** [comment]
Thanks I'll try. I thought I already had it installed when I installed
unity but I'll recheck.

**Comment by pikachuk** [comment]
not really, since Unity Engine uses mono framework, it's not the same as xenko, xenko uses the native .net framework
make sure that you have installed it
you could try to uninstall and reinstall xenko 3.0 too, i had the same install error but it goes away after reinstalling it

**Comment by xen2** [comment]
This should be fixed in latest Xenko 3.0.0.7 and 3.1 beta (or a few versions before).
Please reopen if you still have the issue after an update.
