### ISSUE TITLE
Game Studio 3.0.0.1 Android build fails on Win 8.1 -- TopDownRPG

### ISSUE THREAD

**Issue by aurodev** [xenko3d/xenko#60]
[C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(609,2)]: Error: The "GetJavaPlatformJar" task was not given a value for the required parameter "AndroidSdkDirectory".

Visual Studio 2017 successfully builds and deploys the APK to the device.

 ( Runs without error but displays blank screen, we suspect the Adreno GPU on this Motorola device is responsible, but this is a separate issue)

**Comment by Cafory** [comment]
Do you solve this question？

**Comment by aurodev** [comment]
> 
> 
> Do you solve this question？
Not from GameStudio.
In VS2017 Android projects build in debug and release, the workaround for release is here: #167
