### ISSUE TITLE
Add instructions for compiling and running the Xenko editor from source

### ISSUE THREAD

**Issue by aaronfranke** [xenko3d/xenko#61]
Currently, the [Building from source](https://github.com/xenko3d/xenko/blob/master/README.md#building-from-source) section of README.md has some instructions, but those instructions are not enough. On my system, running the project from within VS causes this error despite compiling fine: 

![untitled](https://user-images.githubusercontent.com/1646875/43696164-5f232b9a-9902-11e8-81ba-8f6ca850c0a8.png)

As the instructions and system requirements say, I have Git installed with Git LFS, VS 2017, Windows 8.1, .NET 4.6.2 Dev tools, C++ desktop dev tools, FBX SDK, and XenkoDir environment variable set correctly. I can run the sample projects fine, and build fine, but I don't see how to run the editor.

**Comment by AirAKose** [comment]
What is your startup project? Many of the projects just generate libraries. The one I've been launching is "Xenko.GameStudio", but I'm not sure if there are other executable projects

**Comment by Kryptos-FR** [comment]
That's not a missing requirements. Just the default project is not set on `Xenko.GameStudio`. Change that and it will work ;-)

**Comment by aaronfranke** [comment]
Changing the launch project to `Xenko.GameStudio` worked. I wouldn't have figured this would be it. I also tried `Xenko.Editor` and that didn't work either.

So either add this to the documentation, or perhaps, change the default project to `Xenko.GameStudio`.

**Comment by xen2** [comment]
That's not something saved by Visual Studio explicitely.

However, I noticed a while ago that the way VS choose this default startup project is by taking the first `csproj` in the solution file.
I remember we had GameStudio at the top for this reason at some point, but seems it got moved around.
Let me fix that.

**Comment by xen2** [comment]
My bad, I remember we did this ordering in the generated user game solution by putting `Windows` project before `Game` one, we never did it for the game studio.

**Comment by aaronfranke** [comment]
Thanks! Glad to see this fixed so quickly. :+1:
