### ISSUE TITLE
Feature request: Add MacOS support

### ISSUE THREAD

**Issue by aaronfranke** [xenko3d/xenko#63]
There's already a few issues open about Linux support, so I thought I'd open one for Mac. I don't personally use Mac, I use Linux and Windows, but I'd still like to be able to export games to MacOS. As far as I can tell, this can be divided into 4 parts:

- [x] Finish and polish existing Linux support first, to make sure it runs well on Unix-like systems.
- [x] Allow exporting games to MacOS from the Windows and Linux editors.
- [x] Implement Metal support via the MoltenVK wrapper for Vulkan.
- [ ] Allow building and running the GameStudio on MacOS.

I'd suggest voting via :+1: if you desire full Mac support. I'd personally only need the first two items.

**Comment by xen2** [comment]
I would go directly for Metal (either by MoltenVK or native implementation) and not even bother with OpenGL.

OpenGL on mac is deprecated. When we tried to do the port we ran into many issues due to shader compilation bugs or missing features.

**Comment by aaronfranke** [comment]
Sounds good, assuming that's the best option. I assumed it would be easier to do Mac OpenGL as a stepping stone to Mac Metal/MoltenVK.

**Comment by phr00t** [comment]
I was all ready to switch to Xenko... until I realized it didn't support exporting to Macs. I don't particularly care about using the GameStudio on a Mac... but I don't want to start a project knowing Mac users will have to be excluded.

**Comment by phr00t** [comment]
I've made a branch where I'll try and find time to make progress on this: https://github.com/phr00t/xenko

**Comment by xen2** [comment]
Quick update, after checking MoltenVK, I retract my comment to go for Metal directly (at least for the time being).
My main concern was the extra step converting shader but it seems MoltenVK has support for prebuilding macOS version at build time too.

Let's just leverage on our Vulkan port, should make it much easier.

**Comment by phr00t** [comment]
I agree, if I have any voting authority xD

**Comment by aaronfranke** [comment]
Metal directly is a waste of time if you can use MoltenVK.

**Comment by phr00t** [comment]
Can this issue be closed, now that Xenko can build for MacOSX & MoltenVK is now used? It doesn't seem like anyone was requiring Mac GameStudio support in this thread (and some talked against it).

**Comment by xen2** [comment]
Yes, let's close this one. We can open new issues if there are bugs/perf issues.

**Comment by tnz81nl** [comment]
The only thing holding me back right now is the limited Mac support. I work primarily with a Windows desktop, but use a MacBook Pro for presentations and development while on the move. I've read it's hard to port the editor (?), but I think it should be a top priority. Many developers use Mac, as well as many artists.

**Comment by shayneoneill** [comment]
While I'm a mac user I would quibble with the idea that many *game* developers use Macs. Artists, absolutely, but devs? I doubt its more than 2-3% of dedicated game devs. (Outside of game dev in regular dev, absolutely theres a tonne of us). So in that regard, I'd suggest it probably isnt something that needs to be a top priority. Being able to port games to a mac, totally, but developing on a mac? Its a bit of a luxury, tbh

**Comment by plotlessplot** [comment]
> While I'm a mac user I would quibble with the idea that many _game_ developers use Macs. Artists, absolutely, but devs? I doubt its more than 2-3% of dedicated game devs. (Outside of game dev in regular dev, absolutely theres a tonne of us). So in that regard, I'd suggest it probably isnt something that needs to be a top priority. Being able to port games to a mac, totally, but developing on a mac? Its a bit of a luxury, tbh

I'd argue that in mobile game development (which is a significant chunk of the games industry in general), it's very common for developers to use Macs as often studios develop and test first on iOS. I've worked in large mobile studios where 50-80% of developers working on Unity and cocos2d games were doing so using a Mac.

For a game engine to become a viable alternative to Unity across the board, it needs first-class mobile support (the vast majority of mobile games are developed in Unity, nowadays) and it needs to fit into these studios' development pipelines with minimal effort, so a Mac editor starts making a ton of sense.

**Comment by muchitto** [comment]
Yeah, I am very much interested in this engine, but I use primarily Mac for development, so not having mac support makes me go looking elsewhere.

**Comment by parhamgholami** [comment]
> Is it really unfeasible to port to something xaml based framework like avalonia or the new maui framework?

There's an active ongoing project to move GameStudio to Avalonia (#2034). I'm not sure what the timeline looks like for that transition, but it looks like that specific barrier is going to be addressed.
