### ISSUE TITLE
Lingering processes after closing Game Studio

### ISSUE THREAD

**Issue by Flavelius** [xenko3d/xenko#66]
Xenko.Core.Assets.CompilerApp_ExecServer and Xenko.EffectCompilerServer, 
as well as some Connection Router, that atleast can be closed via the tray icon.
But these processes stay open after Game Studio is closed.

**Comment by xen2** [comment]
ExecServer should die after a few (10?) minutes. EffectCompilerServer too I think, but not sure.

**Comment by Flavelius** [comment]
Ah, okay, i wasn't aware of that timeout.
