### ISSUE TITLE
Build error "clang.exe is not compatible with the version of Windows you're running"

### ISSUE THREAD

**Issue by gitfool** [xenko3d/xenko#67]
Trying to build `Xenko.Core` with VS 2017 (15.7.6) I get the following build error:
```
1>------ Build started: Project: Xenko.Core, Configuration: Debug Any CPU ------
1>This version of D:\Devel\Repos\Xenko\deps\LLVM\clang.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
1>D:\Devel\Repos\Xenko\sources\native\Xenko.Native.targets(122,5): error MSB3073: The command ""D:\Devel\Repos\Xenko\deps\\LLVM\clang.exe" -gcodeview -fno-ms-extensions -nobuiltininc -nostdinc++  -Wno-ignored-attributes -Wno-delete-non-virtual-dtor -Wno-macro-redefined -I"D:\Devel\Repos\Xenko\deps\\NativePath" -I"D:\Devel\Repos\Xenko\deps\\NativePath\standard" -O0 -g -DNEED_DLL_EXPORT -o "D:\Devel\Repos\Xenko\sources\core\Xenko.Core\obj\Windows-Direct3D11\\x86\CoreNative.obj" -c "D:\Devel\Repos\Xenko\sources\core\Xenko.Core\Native\CoreNative.c" -fms-extensions -DWINDOWS_DESKTOP -target i686-pc-windows-msvc" exited with code 216.
1>Done building project "Xenko.Core.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I'm running Windows 10 1803 (OS Build 17134.167).

**Comment by gitfool** [comment]
Looks like I need to configure git lfs. I'm using the current latest Git for Windows (2.18.0.windows.1).

**Comment by xen2** [comment]
Git LFS should be installed by default on any recent version of Git for Windows. Not sure why it didn't work out for you, maybe you had an old version somewhere that conflicts?

**Comment by Kryptos-FR** [comment]
I also had an issue with an old version of git LFS installed. Some errors appeared in git log when attempting to fetch. So I removed all traces of git and git lfs from my system and just installed the last version of git.

If I remember correctly, the installer doesn't install git LFS by default, so be sure to check the corresponding option.

**Comment by xen2** [comment]
Good to know, I thought it was by default but maybe that's only because I upgrade from a previous version which had it installed.

**Comment by gitfool** [comment]
I must've installed Git for Windows without selecting LFS. I uninstalled it then installed it again and made sure the LFS option was enabled. The git clone looks good now. Thanks guys!
