### ISSUE TITLE
Switch from GitLink to SourceLink to trace into Xenko source code easily

### ISSUE THREAD

**Issue by xen2** [xenko3d/xenko#79]
GitLink allows user to step into Xenko code directly downloaded from GitHub.
It used to work some time ago, shouldn't be hard to have it working again.

Noticed that right now we don't have .pdb anymore in the package, that might be the only thing to fix?

**Comment by gitfool** [comment]
[SourceLink](https://github.com/dotnet/sourcelink)?

**Comment by xen2** [comment]
@gitfool interesting, could be a good alternative.
Seems like it's been opensourced April 2018

**Comment by xen2** [comment]
@gitfool turns out SourceLink is now a much better match for us since we have portable PDB and it seems to be enabled by default in VS. Thanks for pointing it out!
