### ISSUE TITLE
Mesh Collider Shape

### ISSUE THREAD

**Issue by justin330** [xenko3d/xenko#81]
Currently there isn't any method in Xenko for handling collisions with low-poly organic world geometry, like those prominently seen in many great NPR games. (The Legend of Zelda and Mario series, and most indie Unity games).
	
For example a map like Outset Island from Legend of Zelda: Wind Waker HD would be impossible to accurately map collision to its geometry using any of the the provided collider shapes as there isn't a way to adjust its vertices to conform to the target mesh.

**Comment by Kryptos-FR** [comment]
You can generate a convex hull from a low-poly version of your geometry and use it as a collider shape.
https://doc.xenko.com/latest/en/manual/physics/collider-shapes.html

**Comment by justin330** [comment]
![2018-08-08_15-32-44](https://user-images.githubusercontent.com/9954903/43843859-627019c8-9b20-11e8-9e50-ff77944be299.png)

I wouldn't exactly call this usable...

**Comment by Kryptos-FR** [comment]
In your case, a convex hull is obviously not the right shape. But as I said, you can use a lower poly version of your model as a collider shape.

**Comment by xen2** [comment]
Otherwise you could split this object in several convex-friendly models (i.e. the island on the left, the island on the right & the lamp?)

**Comment by aurodev** [comment]
But this still creates a convex hull from the asset correct?
A convex hull generated from a from an asset makes it difficult to do closed in geometry like a tube, cave or a building. You would have to piece it together.

Piecing together a complex collider shape from boxes is what is done in the Third Person Platformer demo. There is no mesh collider that I have found. Unless there is some other way to do it other than piecing it together?

@xen2 
@Kryptos-FR

**Comment by aurodev** [comment]
![image](https://user-images.githubusercontent.com/7356383/51272580-762e9b00-1998-11e9-8e22-a16369a3d7e0.png)

**Comment by EternalTamago** [comment]
Hi,

Xenko has the feature that generates multiple convex hulls from a model.
I heard it is disabled because computing it will take a lot of time.

If SimpleWrap = false, it is enabled.
Directly edit the asset file with a text editor to be enabled it.
Or edit and build the source code to exposing some properties.

![01](https://user-images.githubusercontent.com/13661631/51333895-07e5f780-1ac2-11e9-949b-2b16dcdafade.png)

**Comment by xen2** [comment]
Thanks, good find!

If it works, let's expose it.
We probably have to do a few adjustments:
- `SimpleWrap` is not very easy to understand, we should probably rename it
- It seems there is a bunch of other parameters to expose (maybe they should be visible only when VHACD mode is enabled)
Typical way to do that is to create several types sharing a common class/interface. For example, `IConvexHullGenerator` (one implementation for convex hull, one impl for VHACD with VHACD-specific parameters). Then we add this common class/inteface in the `ConvexHullColliderShapeDesc`. If we do this, this will replace `SimpleWrap` parameter.
- our VHACD lib is probably old, it might be a good idea at some point (can be done later)
