### ISSUE TITLE
Can't start Xenko 3 from Xenko Launcher

### ISSUE THREAD

**Issue by Safebox36** [xenko3d/xenko#90]
Assuming that I have all the requisites needed and Xenko installed anything else it needs on its own, I still get this error:

>Check that you have a valid installation with the required workloads, or go to www.visualstudio.com/downloads to install a new one.
>
>System.ArgumentNullException: Value cannot be null. Parameter name: instance at Microsoft.Build.Locator.MSBuildLocator.RegisterInstance(VisualStudioInstance instance) at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults() at Xenko.Core.Assets.PackageSessionPublicHelper.FindAndSetMSBuildVersion() at Xenko.GameStudio.Program.<Startup>d__12.MoveNext()

**Comment by Safebox36** [comment]
Version 3.0.0.0.
Visual Studio 15, Update 3 (MSBuild version unknown but assumed to be highest available for VS15.3).
4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, **4.6.2** (installed twice, once independently and once along with the launcher). Runtime and SDK for all versions have been installed.

Both Xenko Studio and the Xenko Launcher have been uninstalled and reinstalled twice. Visual Studio has been repaired and third-party extensions have been updated in case that was an issue.

**Comment by Kryptos-FR** [comment]
You need MSBuild 2017 (ideally VS 2017 too). There is a prompt to install it the first time a Xenko package is installed. Don't close it and let it do the installation. 

And I assume you meant VS 2015 not VS 15. I know it is confusing, but the actual numbering is Vs 205 = VS 14 and VS 2017 = VS 15.

**Comment by Safebox36** [comment]
Ah, yes I meant VS 2015. Sorry, my bad. I can't install 2017 because the lowest OS it supports is Windows 10 and I'm on Windows 8 (thank you Microsoft for your lack of support).

Oddly enough, the minimum requirements specified for Xenko list Windows 7 onwards, but is that just referring to the launcher?

**Comment by Kryptos-FR** [comment]
You mean you are on Windows 8.0? That OS is not supported for ages, there were free upgrades to 8.1 at some point I think. Don't expect to run anything on Windows 8.0 nowadays, unfortunately.

Visual Studio 2017 is supported on Windows 7, Windows 8.1 and Windows 10, as is Xenko.
https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs

**Comment by Safebox36** [comment]
I never upgraded to 8.1 because at the time nothing I had installed worked on it and I never got around to upgrading since. I'll update my computer to 8.1 and see if that helps with installing VS 2017 and Xenko 3.

Thanks for clearing that up!

**Comment by Kryptos-FR** [comment]
I hope you can get it to work. Officially Windows 8.0 is not supported by Microsoft since January 2016. Be sure to check online if your hardware is compatible with newer versions or if they are known issues with migrating today. In the worst case, you might still have the option to also downgrade to Windows 7.

Good luck.

**Comment by xen2** [comment]
Closing as not supported (Windows 8.0).
Please let us know if you have issues after upgrading to 8.1
