### ISSUE TITLE
zero change engine build is not minimal

### ISSUE THREAD

**Issue by jmkinzer** [xenko3d/xenko#92]
Performing a build on the engine/editor (e.g. all projects in xenko.sln) with no changes takes a surprising amount of time. Turning msbuild diagnostics shows quite a bit of spew when I expect nothing should occur [as all targets are up-to-date].

The lowest level project I can find that exhibits this issue is Xenko.Native (A build of just this project with no changes reports: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped). Some quick thoughts:
- Is the way Xenko.Native.targets (or related) is setup messing with msbuild up-to-date checks and this is impacting any project with native code?
- Are projects with this type of issue then causing cascading changes further down the line (I haven't looked at the log in detail but I expect so)

Before I spend more time here - I suspect this already well-known and can be explained? I would appreciate any information that can be provided on this. Thanks!

**Comment by xen2** [comment]
It's a known issue and needs to be fixed (likely related to Xenko.Native.targets as you said).

In `Visual Studio > Preferences > Projects and Solutions > .NET Core`, there is Logging level for "up to date" check. This should show what is exactly happening.

**Comment by xen2** [comment]
Additional resources:
* Attempt to fix it a while ago: https://github.com/SiliconStudio/xenko/commit/373fa60909e68f2efa8c783fccecaca395f82320 (maybe this problem came back again in another form with recent changes?)
* Discussion with project-system team to properly generate multiple output files (seems it's not possible yet -- we might have to find another way if one exist)

**Comment by jmkinzer** [comment]
Aha, now I understand the genesis of those "workaround" comments. Thanks.
> "... properly generate multiple output files"
Sorry, not clear to me what you mean here. Can you expand on that?

I will see if I can make headway here.

BTW, I noticed other issues here and there (e.g. took a couple build 'iterations' to get to a working compile at least for the full xenko solution, exec server seemed a little flaky) but this seems like a good place to start. If you know of / have existing info on other known build problems and want to create issues for them I think that would be useful. IMO to encourage contributions the engine needs to be as comfortable to hack on as possible.

**Comment by xen2** [comment]
And yes, totally agree build should work smoothly out of the box without any tweaking.

This was already important before but it's even more of a priority now that we are MIT, to lower barrier of entry.

**Comment by xen2** [comment]
Fixed with b04c4b52
