### ISSUE TITLE
Unable to add MP3 Media Assets

### ISSUE THREAD

**Issue by GhostSource** [xenko3d/xenko#95]
Hi folks,
I'd like to report a bug which I determined yesterday (see [Forum thread](http://answers.xenko.com/questions/3030/unable-to-add-mp3-media-assets.html)).
In the latest version of the game studio (3.0.0.3), it is not possible to add MP3 media assets as described in the documentation ([Import audio](https://doc.xenko.com/latest/en/manual/audio/import-audio.html)). As soon as the required MP3 file is selected in the file browser, the following error message appeares:

**Error: An exception occurred while generating the template.. System.OverflowException: Arithmetic operation resulted in an overflow.**

The error message appeares when choosing "Music", "Spatialized" as well as "Sound effect" assets.

WAV format seems to work (I converted my MP3 files to it), I didn't try the other supported formats yet.

Best, GS

**Comment by Kryptos-FR** [comment]
I did a quick investigation and it seems like for some reason ffmpeg believes there might be a video stream and then when trying to decode it computes a NaN which causes the exception.

I will push a quick hotfix, but we need further investigation to properly fix it. The thing is that ffmpeg library is quick obscure and hard to use and its documentation is not always helpful (if not confusing).

Note: we use ffmpeg to extract audio/video frames from the resource files.
